env = {
  'AR': 'lib',
  'ARCOM': "${TEMPFILE('$AR $ARFLAGS /OUT:$TARGET $SOURCES')}",
  'ARFLAGS': ['/nologo'],
  'AS': '"C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\bin\\amd64\\ml64.exe"',
  'ASCOM': '$AS $ASFLAGS /c /Fo$TARGET $SOURCES',
  'ASFLAGS': ['/nologo'],
  'ASPPCOM': '$CC $ASPPFLAGS $CPPFLAGS $_CPPDEFFLAGS $_CPPINCFLAGS /c /Fo$TARGET $SOURCES',
  'ASPPFLAGS': '$ASFLAGS',
  # 'BUILDERS': {'CopyAs': <SCons.Builder.BuilderBase object at 0x00000000032392E8>, 'SharedLibrary': <SCons.Builder.BuilderBase object at 0x000000000322C860>, 'Zip': <SCons.Builder.BuilderBase object at 0x000000000322C1D0>, 'MSVSProject': <SCons.Builder.BuilderBase object at 0x00000000031D5BE0>, 'RES': <SCons.Builder.BuilderBase object at 0x00000000031D5DA0>, 'TypeLibrary': <SCons.Builder.BuilderBase object at 0x00000000031F0240>, 'Object': <SCons.Builder.CompositeBuilder object at 0x00000000032330F0>, 'Jar': <SCons.Builder.BuilderBase object at 0x00000000032393C8>, 'PCH': <SCons.Builder.BuilderBase object at 0x0000000003173748>, 'StaticLibrary': <SCons.Builder.BuilderBase object at 0x00000000032336A0>, 'RMIC': <SCons.Builder.BuilderBase object at 0x0000000003213748>, 'JavaClassFile': <SCons.Builder.BuilderBase object at 0x0000000003239588>, 'CopyTo': <SCons.Builder.BuilderBase object at 0x00000000032392B0>, 'Program': <SCons.Builder.BuilderBase object at 0x000000000322C940>, 'Library': <SCons.Builder.BuilderBase object at 0x00000000032336A0>, 'SharedObject': <SCons.Builder.CompositeBuilder object at 0x0000000003233240>, 'JavaClassDir': <SCons.Builder.BuilderBase object at 0x0000000003239630>, 'JavaFile': <SCons.Builder.CompositeBuilder object at 0x00000000032394E0>, 'StaticObject': <SCons.Builder.CompositeBuilder object at 0x00000000032330F0>, 'MSVSSolution': <SCons.Builder.BuilderBase object at 0x00000000031D5CF8>, 'LoadableModule': <SCons.Builder.BuilderBase object at 0x000000000322CAC8>},
  # 'BUILD_PATH': 'C:\\Cygwin\\home\\Administrator\\embedded-app-test\\build\\embedded',
  'CC': 'cl',
  'CCCOM': '${TEMPFILE("$CC $_MSVC_OUTPUT_FLAG /c $CHANGED_SOURCES $CFLAGS $CCFLAGS $_CCCOMCOM")}',
  'CCFLAGS': ['/nologo'],
  'CCPCHFLAGS': ['${(PCH and "/Yu%s \\"/Fp%s\\""%(PCHSTOP or "",File(PCH))) or ""}'],
  'CCPDBFLAGS': ['${(PDB and "/Z7") or ""}'],
  'CFILESUFFIX': '.c',
  'CFLAGS': [],
  'CONFIGUREDIR': '#/.sconf_temp',
  'CONFIGURELOG': '#/config.log',
  'COPYSTR': 'Copy file(s): "$SOURCES" to "$TARGETS"',
  'CPPDEFPREFIX': '/D',
  'CPPDEFSUFFIX': '',
  # 'CPPFLAGS': [ '/IC:\\Cygwin\\home\\Administrator\\embedded-app-test\\parts\\python\\include'],
  'CPPPATH': ['#python/Include', '$BUILD_PATH', '#python/PC'],
  'CPPSUFFIXES': [ '.c',
                   '.C',
                   '.cxx',
                   '.cpp',
                   '.c++',
                   '.cc',
                   '.h',
                   '.H',
                   '.hxx',
                   '.hpp',
                   '.hh',
                   '.F',
                   '.fpp',
                   '.FPP',
                   '.m',
                   '.mm',
                   '.S',
                   '.spp',
                   '.SPP',
                   '.sx'],
  'CXX': '$CC',
  'CXXCOM': '${TEMPFILE("$CXX $_MSVC_OUTPUT_FLAG /c $CHANGED_SOURCES $CXXFLAGS $CCFLAGS $_CCCOMCOM")}',
  'CXXFILESUFFIX': '.cc',
  'CXXFLAGS': ['$(', '/TP', '$)'],
  'DOUBLE_ENDIAN': 'auto',
  'DSUFFIXES': ['.d'],
  # 'Dir': <SCons.Defaults.Variable_Method_Caller object at 0x0000000002BC8780>,
  # 'Dirs': <SCons.Defaults.Variable_Method_Caller object at 0x0000000002BC87B8>,
  'ENV': { 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
           'INCLUDE': 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\ATLMFC\\INCLUDE;C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\INCLUDE;C:\\Program Files\\Microsoft SDKs\\Windows\\v7.0\\include',
           'LIB': 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\ATLMFC\\LIB\\amd64;C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\LIB\\amd64;C:\\Program Files\\Microsoft SDKs\\Windows\\v7.0\\lib\\x64',
           'LIBPATH': 'C:\\WINDOWS\\Microsoft.NET\\Framework64\\v3.5;C:\\WINDOWS\\Microsoft.NET\\Framework64\\v2.0.50727;C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\ATLMFC\\LIB\\amd64;C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\LIB\\amd64',
           'PATH': 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BIN\\amd64;C:\\WINDOWS\\Microsoft.NET\\Framework64\\v3.5;C:\\WINDOWS\\Microsoft.NET\\Framework64\\v3.5\\Microsoft .NET Framework 3.5 (Pre-Release Version);C:\\WINDOWS\\Microsoft.NET\\Framework64\\v2.0.50727;C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\VCPackages;C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\Common7\\IDE;C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\Common7\\Tools;C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\Common7\\Tools\\bin;C:\\Program Files\\Microsoft SDKs\\Windows\\v7.0\\bin\\x64;C:\\Program Files\\Microsoft SDKs\\Windows\\v7.0\\bin\\win64\\x64;C:\\Program Files\\Microsoft SDKs\\Windows\\v7.0\\bin;C:\\WINDOWS\\System32',
           'PATHEXT': '.COM;.EXE;.BAT;.CMD',
           'SystemDrive': 'C:',
           'SystemRoot': 'C:\\WINDOWS',
           'TEMP': 'C:\\Users\\ADMINI~1\\LOCALS~1\\Temp',
           'TMP': 'C:\\Users\\ADMINI~1\\LOCALS~1\\Temp'},
  # 'ESCAPE': <function escape at 0x000000000306BDD8>,
  # 'EXTERNAL_C_MODULES_FILE': 'C:\\Cygwin\\home\\Administrator\\embedded-app-test\\build\\embedded\\c_modules.json',
  # 'EXTERNAL_PY_MODULES_FILE': 'C:\\Cygwin\\home\\Administrator\\embedded-app-test\\build\\embedded\\python_files.json',
  'F03': 'gfortran',
  'F03COM': '$F03 -o $TARGET -c $F03FLAGS $_F03INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'F03FLAGS': [],
  'F03PPCOM': '$F03 -o $TARGET -c $F03FLAGS $CPPFLAGS $_CPPDEFFLAGS $_F03INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'F77': 'gfortran',
  'F77COM': '$F77 -o $TARGET -c $F77FLAGS $_F77INCFLAGS $SOURCES',
  'F77FLAGS': [],
  'F77PPCOM': '$F77 -o $TARGET -c $F77FLAGS $CPPFLAGS $_CPPDEFFLAGS $_F77INCFLAGS $SOURCES',
  'F90': 'gfortran',
  'F90COM': '$F90 -o $TARGET -c $F90FLAGS $_F90INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'F90FLAGS': [],
  'F90PPCOM': '$F90 -o $TARGET -c $F90FLAGS $CPPFLAGS $_CPPDEFFLAGS $_F90INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'F95': 'gfortran',
  'F95COM': '$F95 -o $TARGET -c $F95FLAGS $_F95INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'F95FLAGS': [],
  'F95PPCOM': '$F95 -o $TARGET -c $F95FLAGS $CPPFLAGS $_CPPDEFFLAGS $_F95INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'FORTRAN': 'gfortran',
  'FORTRANCOM': '$FORTRAN -o $TARGET -c $FORTRANFLAGS $_FORTRANINCFLAGS $_FORTRANMODFLAG $SOURCES',
  'FORTRANFLAGS': [],
  'FORTRANMODDIR': '',
  'FORTRANMODDIRPREFIX': '',
  'FORTRANMODDIRSUFFIX': '',
  'FORTRANMODPREFIX': '',
  'FORTRANMODSUFFIX': '.mod',
  'FORTRANPPCOM': '$FORTRAN -o $TARGET -c $FORTRANFLAGS $CPPFLAGS $_CPPDEFFLAGS $_FORTRANINCFLAGS $_FORTRANMODFLAG $SOURCES',
  'FORTRANSUFFIXES': [ '.f',
                       '.for',
                       '.ftn',
                       '.F',
                       '.FOR',
                       '.FTN',
                       '.fpp',
                       '.FPP',
                       '.f77',
                       '.F77',
                       '.f90',
                       '.F90',
                       '.f95',
                       '.F95',
                       '.f03',
                       '.F03'],
  # 'File': <SCons.Defaults.Variable_Method_Caller object at 0x0000000002BC87F0>,
  'GETPATH_EXEC_PREFIX': None,
  'GETPATH_LANDMARK': None,
  'GETPATH_PREFIX': None,
  'GETPATH_PYTHONPATH': None,
  'GETPATH_VERSION': '2.7',
  # 'GET_MSVSPROJECTSUFFIX': <function GetMSVSProjectSuffix at 0x00000000031DA588>,
  # 'GET_MSVSSOLUTIONSUFFIX': <function GetMSVSSolutionSuffix at 0x00000000031DA5F8>,
  # 'HAVE_CURSES': False,
  # 'HAVE_CURSES_PANEL': False,
  # 'HAVE_LIBBZ2': True,
  # 'HAVE_LIBCABINET': True,
  # 'HAVE_LIBCRYPT': False,
  # 'HAVE_LIBDB': False,
  # 'HAVE_LIBEXPAT': False,
  # 'HAVE_LIBGDBM': False,
  # 'HAVE_LIBM': True,
  # 'HAVE_LIBMSI': False,
  # 'HAVE_LIBNDBM': False,
  # 'HAVE_LIBNSL': True,
  # 'HAVE_LIBRPCRT4': True,
  # 'HAVE_LIBSQLITE3': True,
  # 'HAVE_LIBTCL': False,
  # 'HAVE_LIBTK': False,
  # 'HAVE_LIBWS32_32': True,
  # 'HAVE_LIBZ': True,
  # 'HAVE_OPENSSL': True,
  # 'HAVE_READLINE': False,
  'HOST_ARCH': 'x86_64',
  'HOST_OS': 'win32',
  'IDLSUFFIXES': ['.idl', '.IDL'],
  'INCF03PREFIX': '-I',
  'INCF03SUFFIX': '',
  'INCF77PREFIX': '-I',
  'INCF77SUFFIX': '',
  'INCF90PREFIX': '-I',
  'INCF90SUFFIX': '',
  'INCF95PREFIX': '-I',
  'INCF95SUFFIX': '',
  'INCFORTRANPREFIX': '-I',
  'INCFORTRANSUFFIX': '',
  'INCPREFIX': '/I',
  'INCSUFFIX': '',
  'JAR': 'jar',
  'JARCOM': "${TEMPFILE('$_JARCOM')}",
  'JARFLAGS': ['cf'],
  'JARSUFFIX': '.jar',
  'JAVABOOTCLASSPATH': [],
  'JAVAC': 'javac',
  'JAVACCOM': "${TEMPFILE('$_JAVACCOM')}",
  'JAVACFLAGS': [],
  'JAVACLASSPATH': [],
  'JAVACLASSSUFFIX': '.class',
  'JAVASOURCEPATH': [],
  'JAVASUFFIX': '.java',
  'LDMODULE': '$SHLINK',
  # 'LDMODULECOM': <SCons.Action.ListAction object at 0x00000000031DFC50>,
  # 'LDMODULEEMITTER': [<function ldmodEmitter at 0x00000000031E14A8>],
  'LDMODULEFLAGS': '$SHLINKFLAGS',
  'LDMODULEPREFIX': '$SHLIBPREFIX',
  'LDMODULESUFFIX': '$SHLIBSUFFIX',
  'LIBDIRPREFIX': '/LIBPATH:',
  'LIBDIRSUFFIX': '',
  'LIBLINKPREFIX': '',
  'LIBLINKSUFFIX': '$LIBSUFFIX',
  # 'LIBPATH': [ 'C:\\Cygwin\\home\\Administrator\\embedded-app-test\\build\\static'],
  'LIBPREFIX': '',
  'LIBPREFIXES': ['$LIBPREFIX'],
  'LIBS': [ 'libevent_core',
            'libevent',
            'libexslt',
            'libxslt',
            'libxml2',
            'sqlite3',
            'bz2',
            'charset',
            'iconv',
            'intl',
            'asprintf',
            'libeay32',
            'ssleay32',
            'zdll',
            'zlib'],
  'LIBSUFFIX': '.lib',
  'LIBSUFFIXES': ['$LIBSUFFIX'],
  'LINK': 'link',
  # 'LINKCOM': <SCons.Action.ListAction object at 0x00000000031DFC88>,
  'LINKFLAGS': ['/nologo'],
  'MAXLINELENGTH': 2048,
  'MIDL': 'MIDL.EXE',
  'MIDLCOM': '$MIDL $MIDLFLAGS /tlb ${TARGETS[0]} /h ${TARGETS[1]} /iid ${TARGETS[2]} /proxy ${TARGETS[3]} /dlldata ${TARGETS[4]} $SOURCE 2> NUL',
  'MIDLFLAGS': ['/nologo'],
  'MSVC_SETUP_RUN': True,
  'MSVC_VERSION': '9.0',
  'MSVS': { 'PROJECTSUFFIX': '.vcproj', 'SOLUTIONSUFFIX': '.sln'},
  'MSVSBUILDCOM': '$MSVSSCONSCOM "$MSVSBUILDTARGET"',
  'MSVSCLEANCOM': '$MSVSSCONSCOM -c "$MSVSBUILDTARGET"',
  'MSVSENCODING': 'Windows-1252',
  # 'MSVSPROJECTCOM': <SCons.Action.FunctionAction object at 0x00000000031D5AC8>,
  'MSVSPROJECTSUFFIX': '${GET_MSVSPROJECTSUFFIX}',
  'MSVSREBUILDCOM': '$MSVSSCONSCOM "$MSVSBUILDTARGET"',
  # 'MSVSSCONS': '"C:\\Cygwin\\home\\Administrator\\python\\bin\\python.exe" -c "from os.path import join; import sys; sys.path = [ join(sys.prefix, \'Lib\', \'site-packages\', \'scons-2.3.1\'), join(sys.prefix, \'scons-2.3.1\'), join(sys.prefix, \'Lib\', \'site-packages\', \'scons\'), join(sys.prefix, \'scons\') ] + sys.path; import SCons.Script; SCons.Script.main()"',
  'MSVSSCONSCOM': '$MSVSSCONS $MSVSSCONSFLAGS',
  # 'MSVSSCONSCRIPT': <SCons.Node.FS.File object at 0x0000000003060CC0>,
  'MSVSSCONSFLAGS': '-C "${MSVSSCONSCRIPT.dir.abspath}" -f ${MSVSSCONSCRIPT.name}',
  # 'MSVSSOLUTIONCOM': <SCons.Action.FunctionAction object at 0x00000000031D5BA8>,
  'MSVSSOLUTIONSUFFIX': '${GET_MSVSSOLUTIONSUFFIX}',
  'MSVS_VERSION': '9.0',
  'MT': 'mt',
  'MTEXECOM': '-$MT $MTFLAGS -manifest ${TARGET}.manifest $_MANIFEST_SOURCES -outputresource:$TARGET;1',
  'MTFLAGS': ['/nologo'],
  'MTSHLIBCOM': '-$MT $MTFLAGS -manifest ${TARGET}.manifest $_MANIFEST_SOURCES -outputresource:$TARGET;2',
  'OBJPREFIX': '',
  'OBJSUFFIX': '.obj',
  'PCHCOM': '$CXX /Fo${TARGETS[1]} $CXXFLAGS $CCFLAGS $CPPFLAGS $_CPPDEFFLAGS $_CPPINCFLAGS /c $SOURCES /Yc$PCHSTOP /Fp${TARGETS[0]} $CCPDBFLAGS $PCHPDBFLAGS',
  'PCHPDBFLAGS': ['${(PDB and "/Yd") or ""}'],
  # 'PIC_PYTHON_MODULES': True,
  # 'PIC_PYTHON_MODULE_ARRAY': False,
  # 'PIC_PYTHON_MODULE_AUDIOOP': False,
  # 'PIC_PYTHON_MODULE_BINASCII': False,
  # 'PIC_PYTHON_MODULE_BZ2': False,
  # 'PIC_PYTHON_MODULE_CMATH': False,
  # 'PIC_PYTHON_MODULE_CPICKLE': False,
  # 'PIC_PYTHON_MODULE_CRYPT': False,
  # 'PIC_PYTHON_MODULE_CSTRINGIO': False,
  # 'PIC_PYTHON_MODULE_DATETIME': False,
  # 'PIC_PYTHON_MODULE_DBM': False,
  # 'PIC_PYTHON_MODULE_ERRNO': False,
  # 'PIC_PYTHON_MODULE_FCNTL': False,
  # 'PIC_PYTHON_MODULE_FUTURE_BUILTINS': False,
  # 'PIC_PYTHON_MODULE_GC': False,
  # 'PIC_PYTHON_MODULE_GDBM': False,
  # 'PIC_PYTHON_MODULE_GRP': False,
  # 'PIC_PYTHON_MODULE_ITERTOOLS': False,
  # 'PIC_PYTHON_MODULE_LINUXAUDIODEV': False,
  # 'PIC_PYTHON_MODULE_MATH': False,
  # 'PIC_PYTHON_MODULE_MMAP': False,
  # 'PIC_PYTHON_MODULE_MSVCRT': False,
  # 'PIC_PYTHON_MODULE_NIS': False,
  # 'PIC_PYTHON_MODULE_NT': False,
  # 'PIC_PYTHON_MODULE_OPERATOR': False,
  # 'PIC_PYTHON_MODULE_OSSAUDIODEV': False,
  # 'PIC_PYTHON_MODULE_PARSER': False,
  # 'PIC_PYTHON_MODULE_POSIX': False,
  # 'PIC_PYTHON_MODULE_PWD': False,
  # 'PIC_PYTHON_MODULE_PYEXPAT': False,
  # 'PIC_PYTHON_MODULE_READLINE': False,
  # 'PIC_PYTHON_MODULE_RESOURCE': False,
  # 'PIC_PYTHON_MODULE_SELECT': False,
  # 'PIC_PYTHON_MODULE_SIGNAL': False,
  # 'PIC_PYTHON_MODULE_SPWD': False,
  # 'PIC_PYTHON_MODULE_STROP': False,
  # 'PIC_PYTHON_MODULE_SYSLOG': False,
  # 'PIC_PYTHON_MODULE_TERMIOS': False,
  # 'PIC_PYTHON_MODULE_THREAD': False,
  # 'PIC_PYTHON_MODULE_TIME': False,
  # 'PIC_PYTHON_MODULE_UNICODEDATA': False,
  # 'PIC_PYTHON_MODULE_XXSUBTYPE': False,
  # 'PIC_PYTHON_MODULE_ZIPIMPORT': False,
  # 'PIC_PYTHON_MODULE_ZLIB': False,
  # 'PIC_PYTHON_MODULE__BISECT': False,
  # 'PIC_PYTHON_MODULE__BSDDB': False,
  # 'PIC_PYTHON_MODULE__CODECS': False,
  # 'PIC_PYTHON_MODULE__CODECS_CN': False,
  # 'PIC_PYTHON_MODULE__CODECS_HK': False,
  # 'PIC_PYTHON_MODULE__CODECS_ISO2022': False,
  # 'PIC_PYTHON_MODULE__CODECS_JP': False,
  # 'PIC_PYTHON_MODULE__CODECS_KR': False,
  # 'PIC_PYTHON_MODULE__CODECS_TW': False,
  # 'PIC_PYTHON_MODULE__COLLECTIONS': False,
  # 'PIC_PYTHON_MODULE__CSV': False,
  # 'PIC_PYTHON_MODULE__CTYPES': False,
  # 'PIC_PYTHON_MODULE__CTYPES_TEST': False,
  # 'PIC_PYTHON_MODULE__CURSES': False,
  # 'PIC_PYTHON_MODULE__CURSES_PANEL': False,
  # 'PIC_PYTHON_MODULE__ELEMENTTREE': False,
  # 'PIC_PYTHON_MODULE__FUNCTOOLS': False,
  # 'PIC_PYTHON_MODULE__HASHLIB': False,
  # 'PIC_PYTHON_MODULE__HEAPQ': False,
  # 'PIC_PYTHON_MODULE__HOTSHOT': False,
  # 'PIC_PYTHON_MODULE__IO': False,
  # 'PIC_PYTHON_MODULE__JSON': False,
  # 'PIC_PYTHON_MODULE__LOCALE': False,
  # 'PIC_PYTHON_MODULE__LSPROF': False,
  # 'PIC_PYTHON_MODULE__MD5': False,
  # 'PIC_PYTHON_MODULE__MSI': False,
  # 'PIC_PYTHON_MODULE__MULTIBYTECODEC': False,
  # 'PIC_PYTHON_MODULE__MULTIPROCESSING': False,
  # 'PIC_PYTHON_MODULE__RANDOM': False,
  # 'PIC_PYTHON_MODULE__SCPROXY': False,
  # 'PIC_PYTHON_MODULE__SHA': False,
  # 'PIC_PYTHON_MODULE__SHA256': False,
  # 'PIC_PYTHON_MODULE__SHA512': False,
  # 'PIC_PYTHON_MODULE__SOCKET': False,
  # 'PIC_PYTHON_MODULE__SQLITE3': False,
  # 'PIC_PYTHON_MODULE__SRE': False,
  # 'PIC_PYTHON_MODULE__SSL': False,
  # 'PIC_PYTHON_MODULE__STRUCT': False,
  # 'PIC_PYTHON_MODULE__SUBPROCESS': False,
  # 'PIC_PYTHON_MODULE__SYMTABLE': False,
  # 'PIC_PYTHON_MODULE__TESTCAPI': False,
  # 'PIC_PYTHON_MODULE__TKINTER': False,
  # 'PIC_PYTHON_MODULE__WEAKREF': False,
  # 'PIC_PYTHON_MODULE__WINREG': False,
  'PLATFORM': 'win32',
  'PLATFORM_RELEASE': '2003Server',
  # 'PROGEMITTER': [<function prog_emitter at 0x00000000031E1518>],
  'PROGPREFIX': '',
  'PROGSUFFIX': '.exe',
  # 'PSPAWN': <function piped_spawn at 0x000000000306BC88>,
  'PYTHON_DYNLOAD_FILE': None,
  # 'PYTHON_MODULES': [ [<SCons.Node.FS.File object at 0x0000000003EBCE48>],
                      # [<SCons.Node.FS.File object at 0x0000000003EBCE48>],
                      # [<SCons.Node.FS.File object at 0x00000000032CB940>],
                      # [<SCons.Node.FS.File object at 0x00000000035BE8D0>],
                      # [<SCons.Node.FS.File object at 0x00000000035D0BA8>],
                      # [<SCons.Node.FS.File object at 0x00000000035D0B38>],
                      # [<SCons.Node.FS.File object at 0x00000000032AB160>],
                      # [<SCons.Node.FS.File object at 0x00000000032A65F8>],
                      # [<SCons.Node.FS.File object at 0x00000000035D7CF8>],
                      # [<SCons.Node.FS.File object at 0x00000000035D7AC8>],
                      # [<SCons.Node.FS.File object at 0x00000000035DF780>],
                      # [<SCons.Node.FS.File object at 0x00000000035E3E80>],
                      # [<SCons.Node.FS.File object at 0x00000000035E9668>],
                      # [<SCons.Node.FS.File object at 0x00000000035ECFD0>],
                      # [<SCons.Node.FS.File object at 0x00000000035F4908>],
                      # [<SCons.Node.FS.File object at 0x00000000035F81D0>],
                      # [<SCons.Node.FS.File object at 0x0000000003545C88>],
                      # [<SCons.Node.FS.File object at 0x000000000354A978>],
                      # [<SCons.Node.FS.File object at 0x0000000003557320>],
                      # [<SCons.Node.FS.File object at 0x00000000035572B0>],
                      # [<SCons.Node.FS.File object at 0x000000000355E048>],
                      # [<SCons.Node.FS.File object at 0x000000000355DDD8>],
                      # [<SCons.Node.FS.File object at 0x000000000356CCC0>],
                      # [<SCons.Node.FS.File object at 0x000000000356CC50>],
                      # [<SCons.Node.FS.File object at 0x0000000003571C88>],
                      # [<SCons.Node.FS.File object at 0x0000000003576E10>],
                      # [<SCons.Node.FS.File object at 0x000000000385BE80>],
                      # [<SCons.Node.FS.File object at 0x0000000003864320>],
                      # [<SCons.Node.FS.File object at 0x000000000386A588>],
                      # [<SCons.Node.FS.File object at 0x000000000387A128>],
                      # [<SCons.Node.FS.File object at 0x000000000387A0B8>],
                      # [<SCons.Node.FS.File object at 0x000000000387F668>],
                      # [<SCons.Node.FS.File object at 0x0000000003884CF8>],
                      # [<SCons.Node.FS.File object at 0x000000000388BE80>],
                      # [<SCons.Node.FS.File object at 0x00000000038937B8>],
                      # [<SCons.Node.FS.File object at 0x00000000039B0FD0>],
                      # [<SCons.Node.FS.File object at 0x00000000039B89B0>],
                      # [<SCons.Node.FS.File object at 0x00000000039BF5F8>],
                      # [<SCons.Node.FS.File object at 0x0000000003AE5F60>],
                      # [<SCons.Node.FS.File object at 0x0000000003B01748>],
                      # [<SCons.Node.FS.File object at 0x0000000003B016D8>],
                      # [<SCons.Node.FS.File object at 0x0000000003B094A8>],
                      # [<SCons.Node.FS.File object at 0x0000000003B11320>],
                      # [<SCons.Node.FS.File object at 0x0000000003B18358>],
                      # [<SCons.Node.FS.File object at 0x0000000003BB32B0>],
                      # [<SCons.Node.FS.File object at 0x0000000003BBC198>],
                      # [<SCons.Node.FS.File object at 0x0000000003BC4438>],
                      # [<SCons.Node.FS.File object at 0x000000000386A630>],
                      # [<SCons.Node.FS.File object at 0x0000000003BD55F8>],
                      # [<SCons.Node.FS.File object at 0x0000000003BDD898>],
                      # [<SCons.Node.FS.File object at 0x0000000003BE4D30>],
                      # [<SCons.Node.FS.File object at 0x0000000003D0B198>],
                      # [<SCons.Node.FS.File object at 0x0000000003D13668>],
                      # [<SCons.Node.FS.File object at 0x0000000003D33828>],
                      # [<SCons.Node.FS.File object at 0x0000000003D337B8>],
                      # [<SCons.Node.FS.File object at 0x0000000003D400B8>],
                      # [<SCons.Node.FS.File object at 0x0000000003E902B0>],
                      # [<SCons.Node.FS.File object at 0x0000000003E98CF8>],
                      # [<SCons.Node.FS.File object at 0x0000000003EA2C18>]],
  # 'PYTHON_SOURCE_PATH': 'C:\\Cygwin\\home\\Administrator\\embedded-app-test\\build\\Python-2.7.6',
  'RC': 'rc',
  'RCCOM': '$RC $_CPPDEFFLAGS $_CPPINCFLAGS $RCFLAGS /fo$TARGET $SOURCES',
  'RCFLAGS': [],
  'RCSUFFIXES': ['.rc', '.rc2'],
  # 'RDirs': <SCons.Defaults.Variable_Method_Caller object at 0x0000000002BC8828>,
  'REGSVR': u'C:\\WINDOWS\\System32\\regsvr32',
  # 'REGSVRACTION': <SCons.Action.FunctionAction object at 0x00000000031DFB70>,
  'REGSVRCOM': '$REGSVR $REGSVRFLAGS ${TARGET.windows}',
  'REGSVRFLAGS': '/s ',
  'RMIC': 'rmic',
  'RMICCOM': '$RMIC $RMICFLAGS -d ${TARGET.attributes.java_lookupdir} -classpath ${SOURCE.attributes.java_classdir} ${SOURCES.attributes.java_classname}',
  'RMICFLAGS': [],
  'SCANNERS': [],
  'SCONS_HOME': None,
  # 'SHARED_PYTHON_MODULES': None,
  # 'SHARED_PYTHON_MODULE_ARRAY': False,
  # 'SHARED_PYTHON_MODULE_AUDIOOP': False,
  # 'SHARED_PYTHON_MODULE_BINASCII': False,
  # 'SHARED_PYTHON_MODULE_BZ2': False,
  # 'SHARED_PYTHON_MODULE_CMATH': False,
  # 'SHARED_PYTHON_MODULE_CPICKLE': False,
  # 'SHARED_PYTHON_MODULE_CRYPT': False,
  # 'SHARED_PYTHON_MODULE_CSTRINGIO': False,
  # 'SHARED_PYTHON_MODULE_DATETIME': False,
  # 'SHARED_PYTHON_MODULE_DBM': False,
  # 'SHARED_PYTHON_MODULE_ERRNO': False,
  # 'SHARED_PYTHON_MODULE_FCNTL': False,
  # 'SHARED_PYTHON_MODULE_FUTURE_BUILTINS': False,
  # 'SHARED_PYTHON_MODULE_GC': False,
  # 'SHARED_PYTHON_MODULE_GDBM': False,
  # 'SHARED_PYTHON_MODULE_GRP': False,
  # 'SHARED_PYTHON_MODULE_ITERTOOLS': False,
  # 'SHARED_PYTHON_MODULE_LINUXAUDIODEV': False,
  # 'SHARED_PYTHON_MODULE_MATH': False,
  # 'SHARED_PYTHON_MODULE_MMAP': False,
  # 'SHARED_PYTHON_MODULE_MSVCRT': False,
  # 'SHARED_PYTHON_MODULE_NIS': False,
  # 'SHARED_PYTHON_MODULE_NT': False,
  # 'SHARED_PYTHON_MODULE_OPERATOR': False,
  # 'SHARED_PYTHON_MODULE_OSSAUDIODEV': False,
  # 'SHARED_PYTHON_MODULE_PARSER': False,
  # 'SHARED_PYTHON_MODULE_POSIX': False,
  # 'SHARED_PYTHON_MODULE_PWD': False,
  # 'SHARED_PYTHON_MODULE_PYEXPAT': False,
  # 'SHARED_PYTHON_MODULE_READLINE': False,
  # 'SHARED_PYTHON_MODULE_RESOURCE': False,
  # 'SHARED_PYTHON_MODULE_SELECT': False,
  # 'SHARED_PYTHON_MODULE_SIGNAL': False,
  # 'SHARED_PYTHON_MODULE_SPWD': False,
  # 'SHARED_PYTHON_MODULE_STROP': False,
  # 'SHARED_PYTHON_MODULE_SYSLOG': False,
  # 'SHARED_PYTHON_MODULE_TERMIOS': False,
  # 'SHARED_PYTHON_MODULE_THREAD': False,
  # 'SHARED_PYTHON_MODULE_TIME': False,
  # 'SHARED_PYTHON_MODULE_UNICODEDATA': False,
  # 'SHARED_PYTHON_MODULE_XXSUBTYPE': False,
  # 'SHARED_PYTHON_MODULE_ZIPIMPORT': False,
  # 'SHARED_PYTHON_MODULE_ZLIB': False,
  # 'SHARED_PYTHON_MODULE__BISECT': False,
  # 'SHARED_PYTHON_MODULE__BSDDB': False,
  # 'SHARED_PYTHON_MODULE__CODECS': False,
  # 'SHARED_PYTHON_MODULE__CODECS_CN': False,
  # 'SHARED_PYTHON_MODULE__CODECS_HK': False,
  # 'SHARED_PYTHON_MODULE__CODECS_ISO2022': False,
  # 'SHARED_PYTHON_MODULE__CODECS_JP': False,
  # 'SHARED_PYTHON_MODULE__CODECS_KR': False,
  # 'SHARED_PYTHON_MODULE__CODECS_TW': False,
  # 'SHARED_PYTHON_MODULE__COLLECTIONS': False,
  # 'SHARED_PYTHON_MODULE__CSV': False,
  # 'SHARED_PYTHON_MODULE__CTYPES': False,
  # 'SHARED_PYTHON_MODULE__CTYPES_TEST': False,
  # 'SHARED_PYTHON_MODULE__CURSES': False,
  # 'SHARED_PYTHON_MODULE__CURSES_PANEL': False,
  # 'SHARED_PYTHON_MODULE__ELEMENTTREE': False,
  # 'SHARED_PYTHON_MODULE__FUNCTOOLS': False,
  # 'SHARED_PYTHON_MODULE__HASHLIB': False,
  # 'SHARED_PYTHON_MODULE__HEAPQ': False,
  # 'SHARED_PYTHON_MODULE__HOTSHOT': False,
  # 'SHARED_PYTHON_MODULE__IO': False,
  # 'SHARED_PYTHON_MODULE__JSON': False,
  # 'SHARED_PYTHON_MODULE__LOCALE': False,
  # 'SHARED_PYTHON_MODULE__LSPROF': False,
  # 'SHARED_PYTHON_MODULE__MD5': False,
  # 'SHARED_PYTHON_MODULE__MSI': False,
  # 'SHARED_PYTHON_MODULE__MULTIBYTECODEC': False,
  # 'SHARED_PYTHON_MODULE__MULTIPROCESSING': False,
  # 'SHARED_PYTHON_MODULE__RANDOM': False,
  # 'SHARED_PYTHON_MODULE__SCPROXY': False,
  # 'SHARED_PYTHON_MODULE__SHA': False,
  # 'SHARED_PYTHON_MODULE__SHA256': False,
  # 'SHARED_PYTHON_MODULE__SHA512': False,
  # 'SHARED_PYTHON_MODULE__SOCKET': False,
  # 'SHARED_PYTHON_MODULE__SQLITE3': False,
  # 'SHARED_PYTHON_MODULE__SRE': False,
  # 'SHARED_PYTHON_MODULE__SSL': False,
  # 'SHARED_PYTHON_MODULE__STRUCT': False,
  # 'SHARED_PYTHON_MODULE__SUBPROCESS': False,
  # 'SHARED_PYTHON_MODULE__SYMTABLE': False,
  # 'SHARED_PYTHON_MODULE__TESTCAPI': False,
  # 'SHARED_PYTHON_MODULE__TKINTER': False,
  # 'SHARED_PYTHON_MODULE__WEAKREF': False,
  # 'SHARED_PYTHON_MODULE__WINREG': False,
  'SHCC': '$CC',
  'SHCCCOM': '${TEMPFILE("$SHCC $_MSVC_OUTPUT_FLAG /c $CHANGED_SOURCES $SHCFLAGS $SHCCFLAGS $_CCCOMCOM")}',
  'SHCCFLAGS': ['$CCFLAGS'],
  'SHCFLAGS': ['$CFLAGS'],
  'SHCXX': '$CXX',
  'SHCXXCOM': '${TEMPFILE("$SHCXX $_MSVC_OUTPUT_FLAG /c $CHANGED_SOURCES $SHCXXFLAGS $SHCCFLAGS $_CCCOMCOM")}',
  'SHCXXFLAGS': ['$CXXFLAGS'],
  'SHELL': u'C:\\WINDOWS\\System32\\cmd.exe',
  'SHF03': '$F03',
  'SHF03COM': '$SHF03 -o $TARGET -c $SHF03FLAGS $_F03INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'SHF03FLAGS': ['$F03FLAGS'],
  'SHF03PPCOM': '$SHF03 -o $TARGET -c $SHF03FLAGS $CPPFLAGS $_CPPDEFFLAGS $_F03INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'SHF77': '$F77',
  'SHF77COM': '$SHF77 -o $TARGET -c $SHF77FLAGS $_F77INCFLAGS $SOURCES',
  'SHF77FLAGS': ['$F77FLAGS'],
  'SHF77PPCOM': '$SHF77 -o $TARGET -c $SHF77FLAGS $CPPFLAGS $_CPPDEFFLAGS $_F77INCFLAGS $SOURCES',
  'SHF90': '$F90',
  'SHF90COM': '$SHF90 -o $TARGET -c $SHF90FLAGS $_F90INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'SHF90FLAGS': ['$F90FLAGS'],
  'SHF90PPCOM': '$SHF90 -o $TARGET -c $SHF90FLAGS $CPPFLAGS $_CPPDEFFLAGS $_F90INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'SHF95': '$F95',
  'SHF95COM': '$SHF95 -o $TARGET -c $SHF95FLAGS $_F95INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'SHF95FLAGS': ['$F95FLAGS'],
  'SHF95PPCOM': '$SHF95 -o $TARGET -c $SHF95FLAGS $CPPFLAGS $_CPPDEFFLAGS $_F95INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'SHFORTRAN': '$FORTRAN',
  'SHFORTRANCOM': '$SHFORTRAN -o $TARGET -c $SHFORTRANFLAGS $_FORTRANINCFLAGS $_FORTRANMODFLAG $SOURCES',
  'SHFORTRANFLAGS': ['$FORTRANFLAGS'],
  'SHFORTRANPPCOM': '$SHFORTRAN -o $TARGET -c $SHFORTRANFLAGS $CPPFLAGS $_CPPDEFFLAGS $_FORTRANINCFLAGS $_FORTRANMODFLAG $SOURCES',
  # 'SHLIBEMITTER': [<function windowsLibEmitter at 0x00000000031E1438>],
  'SHLIBPREFIX': '',
  'SHLIBSUFFIX': '.dll',
  'SHLINK': '$LINK',
  # 'SHLINKCOM': <SCons.Action.ListAction object at 0x00000000031DFBE0>,
  'SHLINKFLAGS': ['$LINKFLAGS', '/dll'],
  'SHOBJPREFIX': '$OBJPREFIX',
  'SHOBJSUFFIX': '$OBJSUFFIX',
  # 'SPAWN': <function spawn at 0x000000000306BD68>,
  # 'STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME': 1,
  # 'STATIC_PYTHON_MODULES': 1,
  # 'STATIC_PYTHON_MODULE_ARRAY': False,
  # 'STATIC_PYTHON_MODULE_AUDIOOP': False,
  # 'STATIC_PYTHON_MODULE_BINASCII': False,
  # 'STATIC_PYTHON_MODULE_BZ2': False,
  # 'STATIC_PYTHON_MODULE_CMATH': False,
  # 'STATIC_PYTHON_MODULE_CPICKLE': False,
  # 'STATIC_PYTHON_MODULE_CRYPT': False,
  # 'STATIC_PYTHON_MODULE_CSTRINGIO': False,
  # 'STATIC_PYTHON_MODULE_DATETIME': False,
  # 'STATIC_PYTHON_MODULE_DBM': False,
  # 'STATIC_PYTHON_MODULE_ERRNO': True,
  # 'STATIC_PYTHON_MODULE_FCNTL': False,
  # 'STATIC_PYTHON_MODULE_FUTURE_BUILTINS': False,
  # 'STATIC_PYTHON_MODULE_GC': True,
  # 'STATIC_PYTHON_MODULE_GDBM': False,
  # 'STATIC_PYTHON_MODULE_GRP': False,
  # 'STATIC_PYTHON_MODULE_INIT_FUNCS': [ u'cjson',
  #                                      u'cjson',
  #                                      '_codecs',
  #                                      'errno',
  #                                      'gc',
  #                                      'signal',
  #                                      '_sre',
  #                                      '_symtable',
  #                                      'nt',
  #                                      'thread',
  #                                      '_weakref',
  #                                      'xxsubtype',
  #                                      'zipimport',
  #                                      'array',
  #                                      'audioop',
  #                                      '_bisect',
  #                                      '_codecs_cn',
  #                                      '_codecs_hk',
  #                                      '_codecs_iso2022',
  #                                      '_codecs_jp',
  #                                      '_codecs_kr',
  #                                      '_codecs_tw',
  #                                      '_collections',
  #                                      'cPickle',
  #                                      'cStringIO',
  #                                      '_csv',
  #                                      'cmath',
  #                                      'datetime',
  #                                      '_functools',
  #                                      'future_builtins',
  #                                      '_heapq',
  #                                      '_hotshot',
  #                                      '_io',
  #                                      'itertools',
  #                                      '_json',
  #                                      '_locale',
  #                                      '_lsprof',
  #                                      'math',
  #                                      'mmap',
  #                                      '_multibytecodec',
  #                                      'operator',
  #                                      'parser',
  #                                      '_random',
  #                                      'strop',
  #                                      '_struct',
  #                                      '_testcapi',
  #                                      'time',
  #                                      'unicodedata',
  #                                      'binascii',
  #                                      'msvcrt',
  #                                      '_subprocess',
  #                                      '_winreg',
  #                                      '_ctypes',
  #                                      '_elementtree',
  #                                      'pyexpat',
  #                                      '_hashlib',
  #                                      'bz2',
  #                                      '_sqlite3',
  #                                      'zlib'],
  # 'STATIC_PYTHON_MODULE_ITERTOOLS': False,
  # 'STATIC_PYTHON_MODULE_LINUXAUDIODEV': False,
  # 'STATIC_PYTHON_MODULE_MATH': False,
  # 'STATIC_PYTHON_MODULE_MMAP': False,
  # 'STATIC_PYTHON_MODULE_MSVCRT': False,
  # 'STATIC_PYTHON_MODULE_NAMES': [ [<SCons.Node.FS.File object at 0x0000000003EBCE48>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003EBCE48>],
  #                                 [<SCons.Node.FS.File object at 0x00000000032CB940>],
  #                                 [<SCons.Node.FS.File object at 0x00000000035BE8D0>],
  #                                 [<SCons.Node.FS.File object at 0x00000000035D0BA8>],
  #                                 [<SCons.Node.FS.File object at 0x00000000035D0B38>],
  #                                 [<SCons.Node.FS.File object at 0x00000000032AB160>],
  #                                 [<SCons.Node.FS.File object at 0x00000000032A65F8>],
  #                                 [<SCons.Node.FS.File object at 0x00000000035D7CF8>],
  #                                 [<SCons.Node.FS.File object at 0x00000000035D7AC8>],
  #                                 [<SCons.Node.FS.File object at 0x00000000035DF780>],
  #                                 [<SCons.Node.FS.File object at 0x00000000035E3E80>],
  #                                 [<SCons.Node.FS.File object at 0x00000000035E9668>],
  #                                 [<SCons.Node.FS.File object at 0x00000000035ECFD0>],
  #                                 [<SCons.Node.FS.File object at 0x00000000035F4908>],
  #                                 [<SCons.Node.FS.File object at 0x00000000035F81D0>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003545C88>],
  #                                 [<SCons.Node.FS.File object at 0x000000000354A978>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003557320>],
  #                                 [<SCons.Node.FS.File object at 0x00000000035572B0>],
  #                                 [<SCons.Node.FS.File object at 0x000000000355E048>],
  #                                 [<SCons.Node.FS.File object at 0x000000000355DDD8>],
  #                                 [<SCons.Node.FS.File object at 0x000000000356CCC0>],
  #                                 [<SCons.Node.FS.File object at 0x000000000356CC50>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003571C88>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003576E10>],
  #                                 [<SCons.Node.FS.File object at 0x000000000385BE80>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003864320>],
  #                                 [<SCons.Node.FS.File object at 0x000000000386A588>],
  #                                 [<SCons.Node.FS.File object at 0x000000000387A128>],
  #                                 [<SCons.Node.FS.File object at 0x000000000387A0B8>],
  #                                 [<SCons.Node.FS.File object at 0x000000000387F668>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003884CF8>],
  #                                 [<SCons.Node.FS.File object at 0x000000000388BE80>],
  #                                 [<SCons.Node.FS.File object at 0x00000000038937B8>],
  #                                 [<SCons.Node.FS.File object at 0x00000000039B0FD0>],
  #                                 [<SCons.Node.FS.File object at 0x00000000039B89B0>],
  #                                 [<SCons.Node.FS.File object at 0x00000000039BF5F8>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003AE5F60>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003B01748>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003B016D8>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003B094A8>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003B11320>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003B18358>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003BB32B0>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003BBC198>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003BC4438>],
  #                                 [<SCons.Node.FS.File object at 0x000000000386A630>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003BD55F8>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003BDD898>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003BE4D30>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003D0B198>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003D13668>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003D33828>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003D337B8>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003D400B8>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003E902B0>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003E98CF8>],
  #                                 [<SCons.Node.FS.File object at 0x0000000003EA2C18>]],
  # 'STATIC_PYTHON_MODULE_NIS': False,
  # 'STATIC_PYTHON_MODULE_NT': True,
  # 'STATIC_PYTHON_MODULE_OBJECTS': [ [<SCons.Node.FS.File object at 0x0000000003EC28D0>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003EC28D0>],
  #                                   [<SCons.Node.FS.File object at 0x00000000035BE6D8>],
  #                                   [<SCons.Node.FS.File object at 0x00000000035D09B0>],
  #                                   [<SCons.Node.FS.File object at 0x00000000035D2BE0>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003297F28>],
  #                                   [<SCons.Node.FS.File object at 0x00000000032A6470>],
  #                                   [<SCons.Node.FS.File object at 0x00000000035D79E8>],
  #                                   [<SCons.Node.FS.File object at 0x00000000035D80B8>],
  #                                   [<SCons.Node.FS.File object at 0x00000000035DF6A0>],
  #                                   [<SCons.Node.FS.File object at 0x00000000035E3DD8>],
  #                                   [<SCons.Node.FS.File object at 0x00000000035E95C0>],
  #                                   [<SCons.Node.FS.File object at 0x00000000035ECE10>],
  #                                   [<SCons.Node.FS.File object at 0x00000000035F4780>],
  #                                   [<SCons.Node.FS.File object at 0x00000000035F8128>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003545BA8>],
  #                                   [<SCons.Node.FS.File object at 0x000000000354A8D0>],
  #                                   [<SCons.Node.FS.File object at 0x00000000035514A8>],
  #                                   [<SCons.Node.FS.File object at 0x00000000035571D0>],
  #                                   [<SCons.Node.FS.File object at 0x000000000355BF60>],
  #                                   [<SCons.Node.FS.File object at 0x000000000355DD30>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003567BA8>],
  #                                   [<SCons.Node.FS.File object at 0x000000000356CB70>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003571BE0>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003576C50>],
  #                                   [<SCons.Node.FS.File object at 0x000000000385BDD8>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003861FD0>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003864198>],
  #                                   [<SCons.Node.FS.File object at 0x000000000386A4A8>],
  #                                   [<SCons.Node.FS.File object at 0x000000000386A668>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003871A90>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003876F98>],
  #                                   [<SCons.Node.FS.File object at 0x000000000387F588>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003884B38>],
  #                                   [<SCons.Node.FS.File object at 0x000000000388B3C8>],
  #                                   [<SCons.Node.FS.File object at 0x000000000388B550>],
  #                                   [<SCons.Node.FS.File object at 0x000000000388B6D8>],
  #                                   [<SCons.Node.FS.File object at 0x000000000388B860>],
  #                                   [<SCons.Node.FS.File object at 0x000000000388B9E8>],
  #                                   [<SCons.Node.FS.File object at 0x000000000388BB70>],
  #                                   [<SCons.Node.FS.File object at 0x000000000388BCF8>],
  #                                   [<SCons.Node.FS.File object at 0x00000000038935C0>],
  #                                   [<SCons.Node.FS.File object at 0x00000000039B0F28>],
  #                                   [<SCons.Node.FS.File object at 0x00000000039B88D0>],
  #                                   [<SCons.Node.FS.File object at 0x00000000039BF358>],
  #                                   [<SCons.Node.FS.File object at 0x00000000039BF518>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003861FD0>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003AE5EB8>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003AFA8D0>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003B015F8>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003B09400>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003B11240>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003B18160>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003BB3128>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003BBC0F0>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003BC4240>],
  #                                   [<SCons.Node.FS.File object at 0x000000000386A668>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003BD5550>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003BDD7F0>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003BE4C50>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003D0B0F0>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003D135C0>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003D1ACF8>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003D1AE80>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003D20048>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003D201D0>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003D20358>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003D20860>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003D20BA8>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003D20D30>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003D20EB8>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003D336D8>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003D3DFD0>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003D40390>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003D40518>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003D406A0>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003E900B8>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003E98B70>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003EA2860>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003EA29E8>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003EA2B70>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003EA2DA0>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003EA2F60>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003EAB1D0>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003EAB390>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003EAB518>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003EAB6A0>],
  #                                   [<SCons.Node.FS.File object at 0x0000000003233630>]],
  # 'STATIC_PYTHON_MODULE_OPERATOR': False,
  # 'STATIC_PYTHON_MODULE_OSSAUDIODEV': False,
  # 'STATIC_PYTHON_MODULE_PARSER': False,
  # 'STATIC_PYTHON_MODULE_POSIX': True,
  # 'STATIC_PYTHON_MODULE_PWD': False,
  # 'STATIC_PYTHON_MODULE_PYEXPAT': False,
  # 'STATIC_PYTHON_MODULE_READLINE': False,
  # 'STATIC_PYTHON_MODULE_RESOURCE': False,
  # 'STATIC_PYTHON_MODULE_SELECT': False,
  # 'STATIC_PYTHON_MODULE_SIGNAL': True,
  # 'STATIC_PYTHON_MODULE_SPWD': False,
  # 'STATIC_PYTHON_MODULE_STROP': False,
  # 'STATIC_PYTHON_MODULE_SYSLOG': False,
  # 'STATIC_PYTHON_MODULE_TERMIOS': False,
  # 'STATIC_PYTHON_MODULE_THREAD': True,
  # 'STATIC_PYTHON_MODULE_TIME': False,
  # 'STATIC_PYTHON_MODULE_UNICODEDATA': False,
  # 'STATIC_PYTHON_MODULE_XXSUBTYPE': True,
  # 'STATIC_PYTHON_MODULE_ZIPIMPORT': True,
  # 'STATIC_PYTHON_MODULE_ZLIB': False,
  # 'STATIC_PYTHON_MODULE__BISECT': False,
  # 'STATIC_PYTHON_MODULE__BSDDB': False,
  # 'STATIC_PYTHON_MODULE__CODECS': True,
  # 'STATIC_PYTHON_MODULE__CODECS_CN': False,
  # 'STATIC_PYTHON_MODULE__CODECS_HK': False,
  # 'STATIC_PYTHON_MODULE__CODECS_ISO2022': False,
  # 'STATIC_PYTHON_MODULE__CODECS_JP': False,
  # 'STATIC_PYTHON_MODULE__CODECS_KR': False,
  # 'STATIC_PYTHON_MODULE__CODECS_TW': False,
  # 'STATIC_PYTHON_MODULE__COLLECTIONS': False,
  # 'STATIC_PYTHON_MODULE__CSV': False,
  # 'STATIC_PYTHON_MODULE__CTYPES': False,
  # 'STATIC_PYTHON_MODULE__CTYPES_TEST': False,
  # 'STATIC_PYTHON_MODULE__CURSES': False,
  # 'STATIC_PYTHON_MODULE__CURSES_PANEL': False,
  # 'STATIC_PYTHON_MODULE__ELEMENTTREE': False,
  # 'STATIC_PYTHON_MODULE__FUNCTOOLS': False,
  # 'STATIC_PYTHON_MODULE__HASHLIB': False,
  # 'STATIC_PYTHON_MODULE__HEAPQ': False,
  # 'STATIC_PYTHON_MODULE__HOTSHOT': False,
  # 'STATIC_PYTHON_MODULE__IO': False,
  # 'STATIC_PYTHON_MODULE__JSON': False,
  # 'STATIC_PYTHON_MODULE__LOCALE': False,
  # 'STATIC_PYTHON_MODULE__LSPROF': False,
  # 'STATIC_PYTHON_MODULE__MD5': False,
  # 'STATIC_PYTHON_MODULE__MSI': False,
  # 'STATIC_PYTHON_MODULE__MULTIBYTECODEC': False,
  # 'STATIC_PYTHON_MODULE__MULTIPROCESSING': False,
  # 'STATIC_PYTHON_MODULE__RANDOM': False,
  # 'STATIC_PYTHON_MODULE__SCPROXY': False,
  # 'STATIC_PYTHON_MODULE__SHA': False,
  # 'STATIC_PYTHON_MODULE__SHA256': False,
  # 'STATIC_PYTHON_MODULE__SHA512': False,
  # 'STATIC_PYTHON_MODULE__SOCKET': False,
  # 'STATIC_PYTHON_MODULE__SQLITE3': False,
  # 'STATIC_PYTHON_MODULE__SRE': True,
  # 'STATIC_PYTHON_MODULE__SSL': False,
  # 'STATIC_PYTHON_MODULE__STRUCT': False,
  # 'STATIC_PYTHON_MODULE__SUBPROCESS': False,
  # 'STATIC_PYTHON_MODULE__SYMTABLE': True,
  # 'STATIC_PYTHON_MODULE__TESTCAPI': False,
  # 'STATIC_PYTHON_MODULE__TKINTER': False,
  # 'STATIC_PYTHON_MODULE__WEAKREF': True,
  # 'STATIC_PYTHON_MODULE__WINREG': False,
  'TARGET_ARCH': 'amd64',
  'TARGET_OS': None,
  # 'TEMPFILE': <class 'SCons.Platform.TempFileMunge'>,
  'TEMPFILEPREFIX': '@',
  'TOOLS': [ 'default',
             'mslink',
             'msvc',
             'gfortran',
             'masm',
             'mslib',
             'msvs',
             'midl',
             'filesystem',
             'jar',
             'javac',
             'rmic',
             'zip'],
  'UNICODE_SIZE': '2',
  'VERSION': '27',
  'WIN32DEFPREFIX': '',
  'WIN32DEFSUFFIX': '.def',
  'WIN32EXPPREFIX': '',
  'WIN32EXPSUFFIX': '.exp',
  'WIN32_INSERT_DEF': 0,
  'WINDOWSDEFPREFIX': '${WIN32DEFPREFIX}',
  'WINDOWSDEFSUFFIX': '${WIN32DEFSUFFIX}',
  'WINDOWSEXPPREFIX': '${WIN32EXPPREFIX}',
  'WINDOWSEXPSUFFIX': '${WIN32EXPSUFFIX}',
  'WINDOWSPROGMANIFESTPREFIX': '',
  'WINDOWSPROGMANIFESTSUFFIX': '${PROGSUFFIX}.manifest',
  'WINDOWSSHLIBMANIFESTPREFIX': '',
  'WINDOWSSHLIBMANIFESTSUFFIX': '${SHLIBSUFFIX}.manifest',
  'WINDOWS_EMBED_MANIFEST': 0,
  'WINDOWS_INSERT_DEF': '${WIN32_INSERT_DEF}',
  # 'WITH_DL': True,
  # 'WITH_DOC_STRINGS': True,
  # 'WITH_IPV6': True,
  # 'WITH_PYDEBUG': False,
  # 'WITH_PYMALLOC': True,
  # 'WITH_PYTHON_MODULE_ARRAY': True,
  # 'WITH_PYTHON_MODULE_AUDIOOP': True,
  # 'WITH_PYTHON_MODULE_BINASCII': True,
  # 'WITH_PYTHON_MODULE_BZ2': True,
  # 'WITH_PYTHON_MODULE_CMATH': True,
  # 'WITH_PYTHON_MODULE_CPICKLE': True,
  # 'WITH_PYTHON_MODULE_CRYPT': True,
  # 'WITH_PYTHON_MODULE_CSTRINGIO': True,
  # 'WITH_PYTHON_MODULE_DATETIME': True,
  # 'WITH_PYTHON_MODULE_DBM': True,
  # 'WITH_PYTHON_MODULE_ERRNO': True,
  # 'WITH_PYTHON_MODULE_FCNTL': True,
  # 'WITH_PYTHON_MODULE_FUTURE_BUILTINS': True,
  # 'WITH_PYTHON_MODULE_GC': True,
  # 'WITH_PYTHON_MODULE_GDBM': True,
  # 'WITH_PYTHON_MODULE_GRP': True,
  # 'WITH_PYTHON_MODULE_ITERTOOLS': True,
  # 'WITH_PYTHON_MODULE_LINUXAUDIODEV': True,
  # 'WITH_PYTHON_MODULE_MATH': True,
  # 'WITH_PYTHON_MODULE_MMAP': True,
  # 'WITH_PYTHON_MODULE_MSVCRT': True,
  # 'WITH_PYTHON_MODULE_NIS': False,
  # 'WITH_PYTHON_MODULE_NT': True,
  # 'WITH_PYTHON_MODULE_OPERATOR': True,
  # 'WITH_PYTHON_MODULE_OSSAUDIODEV': True,
  # 'WITH_PYTHON_MODULE_PARSER': True,
  # 'WITH_PYTHON_MODULE_POSIX': True,
  # 'WITH_PYTHON_MODULE_PWD': True,
  # 'WITH_PYTHON_MODULE_PYEXPAT': True,
  # 'WITH_PYTHON_MODULE_READLINE': True,
  # 'WITH_PYTHON_MODULE_RESOURCE': True,
  # 'WITH_PYTHON_MODULE_SELECT': True,
  # 'WITH_PYTHON_MODULE_SIGNAL': True,
  # 'WITH_PYTHON_MODULE_SPWD': True,
  # 'WITH_PYTHON_MODULE_STROP': True,
  # 'WITH_PYTHON_MODULE_SYSLOG': True,
  # 'WITH_PYTHON_MODULE_TERMIOS': True,
  # 'WITH_PYTHON_MODULE_THREAD': True,
  # 'WITH_PYTHON_MODULE_TIME': True,
  # 'WITH_PYTHON_MODULE_UNICODEDATA': True,
  # 'WITH_PYTHON_MODULE_XXSUBTYPE': True,
  # 'WITH_PYTHON_MODULE_ZIPIMPORT': True,
  # 'WITH_PYTHON_MODULE_ZLIB': True,
  # 'WITH_PYTHON_MODULE__BISECT': True,
  # 'WITH_PYTHON_MODULE__BSDDB': True,
  # 'WITH_PYTHON_MODULE__CODECS': True,
  # 'WITH_PYTHON_MODULE__CODECS_CN': True,
  # 'WITH_PYTHON_MODULE__CODECS_HK': True,
  # 'WITH_PYTHON_MODULE__CODECS_ISO2022': True,
  # 'WITH_PYTHON_MODULE__CODECS_JP': True,
  # 'WITH_PYTHON_MODULE__CODECS_KR': True,
  # 'WITH_PYTHON_MODULE__CODECS_TW': True,
  # 'WITH_PYTHON_MODULE__COLLECTIONS': True,
  # 'WITH_PYTHON_MODULE__CSV': True,
  # 'WITH_PYTHON_MODULE__CTYPES': True,
  # 'WITH_PYTHON_MODULE__CTYPES_TEST': False,
  # 'WITH_PYTHON_MODULE__CURSES': True,
  # 'WITH_PYTHON_MODULE__CURSES_PANEL': True,
  # 'WITH_PYTHON_MODULE__ELEMENTTREE': True,
  # 'WITH_PYTHON_MODULE__FUNCTOOLS': True,
  # 'WITH_PYTHON_MODULE__HASHLIB': True,
  # 'WITH_PYTHON_MODULE__HEAPQ': True,
  # 'WITH_PYTHON_MODULE__HOTSHOT': True,
  # 'WITH_PYTHON_MODULE__IO': True,
  # 'WITH_PYTHON_MODULE__JSON': True,
  # 'WITH_PYTHON_MODULE__LOCALE': True,
  # 'WITH_PYTHON_MODULE__LSPROF': True,
  # 'WITH_PYTHON_MODULE__MD5': True,
  # 'WITH_PYTHON_MODULE__MSI': True,
  # 'WITH_PYTHON_MODULE__MULTIBYTECODEC': True,
  # 'WITH_PYTHON_MODULE__MULTIPROCESSING': True,
  # 'WITH_PYTHON_MODULE__RANDOM': True,
  # 'WITH_PYTHON_MODULE__SCPROXY': True,
  # 'WITH_PYTHON_MODULE__SHA': True,
  # 'WITH_PYTHON_MODULE__SHA256': True,
  # 'WITH_PYTHON_MODULE__SHA512': True,
  # 'WITH_PYTHON_MODULE__SOCKET': True,
  # 'WITH_PYTHON_MODULE__SQLITE3': True,
  # 'WITH_PYTHON_MODULE__SRE': True,
  # 'WITH_PYTHON_MODULE__SSL': True,
  # 'WITH_PYTHON_MODULE__STRUCT': True,
  # 'WITH_PYTHON_MODULE__SUBPROCESS': True,
  # 'WITH_PYTHON_MODULE__SYMTABLE': True,
  # 'WITH_PYTHON_MODULE__TESTCAPI': True,
  # 'WITH_PYTHON_MODULE__TKINTER': True,
  # 'WITH_PYTHON_MODULE__WEAKREF': True,
  # 'WITH_PYTHON_MODULE__WINREG': True,
  # 'WITH_READLINE': True,
  # 'WITH_SHARED': True,
  # 'WITH_THREAD': True,
  # 'WITH_TSC': False,
  # 'WITH_UNICODE': True,
  # 'WITH_VALGRIND': False,
  'WIXCANDLE': 'candle.exe',
  'WIXLIGHT': 'light.exe',
  'XFLAGS': '',
  'ZIP': 'zip',
  # 'ZIPCOM': <SCons.Action.FunctionAction object at 0x000000000322C198>,
  'ZIPCOMPRESSION': 8,
  'ZIPFLAGS': [],
  'ZIPROOT': [],
  'ZIPSUFFIX': '.zip',
  '_CCCOMCOM': '$CPPFLAGS $_CPPDEFFLAGS $_CPPINCFLAGS $CCPCHFLAGS $CCPDBFLAGS',
  '_CPPDEFFLAGS': '${_defines(CPPDEFPREFIX, CPPDEFINES, CPPDEFSUFFIX, __env__)}',
  '_CPPINCFLAGS': '$( ${_concat(INCPREFIX, CPPPATH, INCSUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
  '_F03INCFLAGS': '$( ${_concat(INCF03PREFIX, F03PATH, INCF03SUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
  '_F77INCFLAGS': '$( ${_concat(INCF77PREFIX, F77PATH, INCF77SUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
  '_F90INCFLAGS': '$( ${_concat(INCF90PREFIX, F90PATH, INCF90SUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
  '_F95INCFLAGS': '$( ${_concat(INCF95PREFIX, F95PATH, INCF95SUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
  '_FORTRANINCFLAGS': '$( ${_concat(INCFORTRANPREFIX, FORTRANPATH, INCFORTRANSUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
  '_FORTRANMODFLAG': '$( ${_concat(FORTRANMODDIRPREFIX, FORTRANMODDIR, FORTRANMODDIRSUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
  '_JARCOM': '$JAR $_JARFLAGS $TARGET $_JARMANIFEST $_JARSOURCES',
  # '_JARFLAGS': <function jarFlags at 0x0000000003209F98>,
  # '_JARMANIFEST': <function jarManifest at 0x0000000003209F28>,
  # '_JARSOURCES': <function jarSources at 0x0000000003209EB8>,
  '_JAVABOOTCLASSPATH': '${_javapathopt("-bootclasspath", "JAVABOOTCLASSPATH")} ',
  '_JAVACCOM': '$JAVAC $JAVACFLAGS $_JAVABOOTCLASSPATH $_JAVACLASSPATH -d ${TARGET.attributes.java_classdir} $_JAVASOURCEPATH $SOURCES',
  '_JAVACLASSPATH': '${_javapathopt("-classpath", "JAVACLASSPATH")} ',
  '_JAVASOURCEPATH': '${_javapathopt("-sourcepath", "JAVASOURCEPATH", "_JAVASOURCEPATHDEFAULT")} ',
  '_JAVASOURCEPATHDEFAULT': '${TARGET.attributes.java_sourcedir}',
  # '_LDMODULE_SOURCES': <function _windowsLdmodSources at 0x00000000031E1358>,
  # '_LDMODULE_TARGETS': <function _windowsLdmodTargets at 0x00000000031E12E8>,
  '_LIBDIRFLAGS': '$( ${_concat(LIBDIRPREFIX, LIBPATH, LIBDIRSUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
  '_LIBFLAGS': '${_concat(LIBLINKPREFIX, LIBS, LIBLINKSUFFIX, __env__)}',
  '_MANIFEST_SOURCES': None,
  # '_MSVC_OUTPUT_FLAG': <function msvc_output_flag at 0x00000000031DAC88>,
  # '_PDB': <function pdbGenerator at 0x00000000031E10B8>,
  # '_SHLINK_SOURCES': <function windowsShlinkSources at 0x00000000031E1278>,
  # '_SHLINK_TARGETS': <function windowsShlinkTargets at 0x00000000031E1208>,
  # '_concat': <function _concat at 0x0000000002BCA588>,
  # '_defines': <function _defines at 0x0000000002BCA748>,
  # '_javapathopt': <class 'SCons.Tool.javac.pathopt'>,
  # '_stripixes': <function _stripixes at 0x0000000002BCA668>}
}
