#!/bin/sh

set -e

exec 3>&1 4>&2

if test "$DEBUG_CUSTOM_ACTIONS" = "1" -o                   \
        -r /tmp/INFINIDAT_DEBUG_CUSTOM_ACTIONS; then
    set -xv
else
    exec > /dev/null 2>&1
fi

if test "$NO_CUSTOM_ACTIONS" = "1" -o                      \
        -r /tmp/INFINIDAT_NO_CUSTOM_ACTIONS; then
    exit 0
fi

echo "Start {{ package }} {{ version }} pre-install script: $0 $@"

ARCH=`dpkg --print-architecture`

if test "$ARCH" != "{{ arch }}"; then
    exec 1>&4 2>&4
    echo "Installation aborted due to CPU architecture mismatch"
    echo "Package {{ package }} {{ version }} built for {{ arch }}"
    echo "Host CPU is $ARCH"
    exit 1
fi

if test "$1" != "upgrade"; then
    exit 0
fi

if test ! -d "{{ prefix }}"; then
    exit 0
fi

cd "{{ prefix }}"

if test ! -x parts/python/bin/python; then
    exit 0
fi

if test -n "{{ close }}" -a "{{ close }}" = "1"; then
    if test -r parts/python/bin/buildout; then
        parts/python/bin/python -I                         \
            parts/python/bin/buildout -U -v install        \
                debug-logging close-application
    fi
fi

exit 0
