#!/bin/sh

set -e

if test "$DEBUG_CUSTOM_ACTIONS" = "1" -o                   \
        -r /tmp/INFINIDAT_DEBUG_CUSTOM_ACTIONS; then
    set -xv
else
    exec > /dev/null 2>&1
fi

if test "$NO_CUSTOM_ACTIONS" = "1" -o                      \
        -r /tmp/INFINIDAT_NO_CUSTOM_ACTIONS; then
    exit 0
fi

echo "Start {{ package }} {{ version }} pre-remove script: $0 $@"

if test "$1" != "remove"; then
    exit 0
fi

{% for script in scripts %}
if test -L "/usr/bin/{{ script }}"; then
    rm -f "/usr/bin/{{ script }}"
fi
{% endfor %}

if test ! -d "{{ prefix }}"; then
    exit 0
fi

cd "{{ prefix }}"

if test ! -x parts/python/bin/python; then
    exit 0
fi

if test -n "{{ pre_uninstall_script_name }}" -a            \
        -r "bin/{{ pre_uninstall_script_name }}"; then
    parts/python/bin/python -I                             \
        "bin/{{ pre_uninstall_script_name }}"              \
            {{ pre_uninstall_script_args }}
fi

if test -n "{{ close }}" -a "{{ close }}" = "1"; then
    if test -r parts/python/bin/buildout; then
        parts/python/bin/python -I                         \
            parts/python/bin/buildout -U -v install        \
                debug-logging close-application
    fi
fi

if parts/python/bin/python -I -m pip --version; then
    parts/python/bin/python -I -m                          \
        pip uninstall --isolated --verbose --yes           \
        pip setuptools wheel zc.buildout
fi

rm -rf .installed.cfg bin develop-eggs eggs                \
    parts/python/lib*/python*/site-packages                \
    src/*.egg-info

find . -type d -name __pycache__ -prune -exec rm -rf {} ";"
find . -type f -name "*.py[co]" -exec rm -f {} ";"

exit 0
