env = {
  'AR': 'lib',
  'ARCOM': "${TEMPFILE('$AR $ARFLAGS /OUT:$TARGET $SOURCES')}",
  'ARFLAGS': ['/nologo'],
  'AS': 'ml',
  'ASCOM': '$AS $ASFLAGS /c /Fo$TARGET $SOURCES',
  'ASFLAGS': ['/nologo'],
  'ASPPCOM': '$CC $ASPPFLAGS $CPPFLAGS $_CPPDEFFLAGS $_CPPINCFLAGS /c /Fo$TARGET $SOURCES',
  'ASPPFLAGS': '$ASFLAGS',
  # 'BUILDERS': {'CopyAs': <SCons.Builder.BuilderBase object at 0x0165CB10>, 'SharedLibrary': <SCons.Builder.BuilderBase object at 0x01648430>, 'Zip': <SCons.Builder.BuilderBase object at 0x01644870>, 'MSVSProject': <SCons.Builder.BuilderBase object at 0x0160B990>, 'RES': <SCons.Builder.BuilderBase object at 0x0160BA50>, 'TypeLibrary': <SCons.Builder.BuilderBase object at 0x01621150>, 'Object': <SCons.Builder.CompositeBuilder object at 0x01648970>, 'Jar': <SCons.Builder.BuilderBase object at 0x0165CBD0>, 'PCH': <SCons.Builder.BuilderBase object at 0x0160B8D0>, 'StaticLibrary': <SCons.Builder.BuilderBase object at 0x0165C9B0>, 'RMIC': <SCons.Builder.BuilderBase object at 0x01634050>, 'JavaClassFile': <SCons.Builder.BuilderBase object at 0x0165CD10>, 'CopyTo': <SCons.Builder.BuilderBase object at 0x0165CAF0>, 'Program': <SCons.Builder.BuilderBase object at 0x016484F0>, 'Library': <SCons.Builder.BuilderBase object at 0x0165C9B0>, 'SharedObject': <SCons.Builder.CompositeBuilder object at 0x01648A10>, 'JavaClassDir': <SCons.Builder.BuilderBase object at 0x0165CDB0>, 'JavaFile': <SCons.Builder.CompositeBuilder object at 0x0165CC70>, 'StaticObject': <SCons.Builder.CompositeBuilder object at 0x01648970>, 'MSVSSolution': <SCons.Builder.BuilderBase object at 0x0160B950>, 'LoadableModule': <SCons.Builder.BuilderBase object at 0x01648910>},
  # 'BUILD_PATH': 'C:\\Cygwin\\home\\Administrator\\embedded-app-test\\build\\embedded',
  'CC': 'cl',
  'CCCOM': '${TEMPFILE("$CC $_MSVC_OUTPUT_FLAG /c $CHANGED_SOURCES $CFLAGS $CCFLAGS $_CCCOMCOM")}',
  'CCFLAGS': ['/nologo'],
  'CCPCHFLAGS': ['${(PCH and "/Yu%s \\"/Fp%s\\""%(PCHSTOP or "",File(PCH))) or ""}'],
  'CCPDBFLAGS': ['${(PDB and "/Z7") or ""}'],
  'CFILESUFFIX': '.c',
  'CFLAGS': [],
  'CONFIGUREDIR': '#/.sconf_temp',
  'CONFIGURELOG': '#/config.log',
  'COPYSTR': 'Copy file(s): "$SOURCES" to "$TARGETS"',
  'CPPDEFPREFIX': '/D',
  'CPPDEFSUFFIX': '',
  # 'CPPFLAGS': [ '/IC:\\Cygwin\\home\\Administrator\\embedded-app-test\\parts\\python\\include'],
  'CPPPATH': ['#python/Include', '$BUILD_PATH', '#python/PC'],
  'CPPSUFFIXES': [ '.c',
                   '.C',
                   '.cxx',
                   '.cpp',
                   '.c++',
                   '.cc',
                   '.h',
                   '.H',
                   '.hxx',
                   '.hpp',
                   '.hh',
                   '.F',
                   '.fpp',
                   '.FPP',
                   '.m',
                   '.mm',
                   '.S',
                   '.spp',
                   '.SPP',
                   '.sx'],
  'CXX': '$CC',
  'CXXCOM': '${TEMPFILE("$CXX $_MSVC_OUTPUT_FLAG /c $CHANGED_SOURCES $CXXFLAGS $CCFLAGS $_CCCOMCOM")}',
  'CXXFILESUFFIX': '.cc',
  'CXXFLAGS': ['$(', '/TP', '$)'],
  'DOUBLE_ENDIAN': 'auto',
  'DSUFFIXES': ['.d'],
  # 'Dir': <SCons.Defaults.Variable_Method_Caller object at 0x0135DA70>,
  # 'Dirs': <SCons.Defaults.Variable_Method_Caller object at 0x0135DA90>,
  'ENV': { 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
           'INCLUDE': 'C:\\Program Files\\Microsoft Visual Studio 9.0\\VC\\ATLMFC\\INCLUDE;C:\\Program Files\\Microsoft Visual Studio 9.0\\VC\\INCLUDE;C:\\Program Files\\Microsoft SDKs\\Windows\\v7.0\\include',
           'LIB': 'C:\\Program Files\\Microsoft Visual Studio 9.0\\VC\\ATLMFC\\LIB;C:\\Program Files\\Microsoft Visual Studio 9.0\\VC\\LIB;C:\\Program Files\\Microsoft SDKs\\Windows\\v7.0\\lib',
           'LIBPATH': 'C:\\WINDOWS\\Microsoft.NET\\Framework\\;C:\\WINDOWS\\Microsoft.NET\\Framework\\v2.0.50727;C:\\Program Files\\Microsoft Visual Studio 9.0\\VC\\ATLMFC\\LIB;C:\\Program Files\\Microsoft Visual Studio 9.0\\VC\\LIB',
           'PATH': 'C:\\Program Files\\Microsoft Visual Studio 9.0\\Common7\\IDE;C:\\Program Files\\Microsoft Visual Studio 9.0\\VC\\BIN;C:\\Program Files\\Microsoft Visual Studio 9.0\\Common7\\Tools;C:\\Program Files\\Microsoft Visual Studio 9.0\\Common7\\Tools\\bin;C:\\WINDOWS\\Microsoft.NET\\Framework\\;C:\\WINDOWS\\Microsoft.NET\\Framework\\\\Microsoft .NET Framework 3.5 (Pre-Release Version);C:\\WINDOWS\\Microsoft.NET\\Framework\\v2.0.50727;C:\\Program Files\\Microsoft Visual Studio 9.0\\VC\\VCPackages;C:\\Program Files\\Microsoft SDKs\\Windows\\v7.0\\bin;C:\\WINDOWS\\System32',
           'PATHEXT': '.COM;.EXE;.BAT;.CMD',
           'SystemDrive': 'C:',
           'SystemRoot': 'C:\\WINDOWS',
           'TEMP': 'C:\\Users\\ADMINI~1\\LOCALS~1\\Temp',
           'TMP': 'C:\\Users\\ADMINI~1\\LOCALS~1\\Temp'},
  # 'ESCAPE': <function escape at 0x015D90B0>,
  # 'EXTERNAL_C_MODULES_FILE': 'C:\\Cygwin\\home\\Administrator\\embedded-app-test\\build\\embedded\\c_modules.json',
  # 'EXTERNAL_PY_MODULES_FILE': 'C:\\Cygwin\\home\\Administrator\\embedded-app-test\\build\\embedded\\python_files.json',
  'F03': 'gfortran',
  'F03COM': '$F03 -o $TARGET -c $F03FLAGS $_F03INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'F03FLAGS': [],
  'F03PPCOM': '$F03 -o $TARGET -c $F03FLAGS $CPPFLAGS $_CPPDEFFLAGS $_F03INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'F77': 'gfortran',
  'F77COM': '$F77 -o $TARGET -c $F77FLAGS $_F77INCFLAGS $SOURCES',
  'F77FLAGS': [],
  'F77PPCOM': '$F77 -o $TARGET -c $F77FLAGS $CPPFLAGS $_CPPDEFFLAGS $_F77INCFLAGS $SOURCES',
  'F90': 'gfortran',
  'F90COM': '$F90 -o $TARGET -c $F90FLAGS $_F90INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'F90FLAGS': [],
  'F90PPCOM': '$F90 -o $TARGET -c $F90FLAGS $CPPFLAGS $_CPPDEFFLAGS $_F90INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'F95': 'gfortran',
  'F95COM': '$F95 -o $TARGET -c $F95FLAGS $_F95INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'F95FLAGS': [],
  'F95PPCOM': '$F95 -o $TARGET -c $F95FLAGS $CPPFLAGS $_CPPDEFFLAGS $_F95INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'FORTRAN': 'gfortran',
  'FORTRANCOM': '$FORTRAN -o $TARGET -c $FORTRANFLAGS $_FORTRANINCFLAGS $_FORTRANMODFLAG $SOURCES',
  'FORTRANFLAGS': [],
  'FORTRANMODDIR': '',
  'FORTRANMODDIRPREFIX': '',
  'FORTRANMODDIRSUFFIX': '',
  'FORTRANMODPREFIX': '',
  'FORTRANMODSUFFIX': '.mod',
  'FORTRANPPCOM': '$FORTRAN -o $TARGET -c $FORTRANFLAGS $CPPFLAGS $_CPPDEFFLAGS $_FORTRANINCFLAGS $_FORTRANMODFLAG $SOURCES',
  'FORTRANSUFFIXES': [ '.f',
                       '.for',
                       '.ftn',
                       '.F',
                       '.FOR',
                       '.FTN',
                       '.fpp',
                       '.FPP',
                       '.f77',
                       '.F77',
                       '.f90',
                       '.F90',
                       '.f95',
                       '.F95',
                       '.f03',
                       '.F03'],
  # 'File': <SCons.Defaults.Variable_Method_Caller object at 0x0135DAB0>,
  'GETPATH_EXEC_PREFIX': None,
  'GETPATH_LANDMARK': None,
  'GETPATH_PREFIX': None,
  'GETPATH_PYTHONPATH': None,
  'GETPATH_VERSION': '2.7',
  # 'GET_MSVSPROJECTSUFFIX': <function GetMSVSProjectSuffix at 0x0160DA30>,
  # 'GET_MSVSSOLUTIONSUFFIX': <function GetMSVSSolutionSuffix at 0x0160DA70>,
  # 'HAVE_CURSES': False,
  # 'HAVE_CURSES_PANEL': False,
  # 'HAVE_LIBBZ2': True,
  # 'HAVE_LIBCABINET': True,
  # 'HAVE_LIBCRYPT': False,
  # 'HAVE_LIBDB': False,
  # 'HAVE_LIBEXPAT': False,
  # 'HAVE_LIBGDBM': False,
  # 'HAVE_LIBM': True,
  # 'HAVE_LIBMSI': False,
  # 'HAVE_LIBNDBM': False,
  # 'HAVE_LIBNSL': True,
  # 'HAVE_LIBRPCRT4': True,
  # 'HAVE_LIBSQLITE3': True,
  # 'HAVE_LIBTCL': False,
  # 'HAVE_LIBTK': False,
  # 'HAVE_LIBWS32_32': True,
  # 'HAVE_LIBZ': True,
  # 'HAVE_OPENSSL': True,
  # 'HAVE_READLINE': False,
  'HOST_ARCH': 'x86',
  'HOST_OS': 'win32',
  'IDLSUFFIXES': ['.idl', '.IDL'],
  'INCF03PREFIX': '-I',
  'INCF03SUFFIX': '',
  'INCF77PREFIX': '-I',
  'INCF77SUFFIX': '',
  'INCF90PREFIX': '-I',
  'INCF90SUFFIX': '',
  'INCF95PREFIX': '-I',
  'INCF95SUFFIX': '',
  'INCFORTRANPREFIX': '-I',
  'INCFORTRANSUFFIX': '',
  'INCPREFIX': '/I',
  'INCSUFFIX': '',
  'JAR': 'jar',
  'JARCOM': "${TEMPFILE('$_JARCOM')}",
  'JARFLAGS': ['cf'],
  'JARSUFFIX': '.jar',
  'JAVABOOTCLASSPATH': [],
  'JAVAC': 'javac',
  'JAVACCOM': "${TEMPFILE('$_JAVACCOM')}",
  'JAVACFLAGS': [],
  'JAVACLASSPATH': [],
  'JAVACLASSSUFFIX': '.class',
  'JAVASOURCEPATH': [],
  'JAVASUFFIX': '.java',
  'LDMODULE': '$SHLINK',
  # 'LDMODULECOM': <SCons.Action.ListAction object at 0x016154F0>,
  # 'LDMODULEEMITTER': [<function ldmodEmitter at 0x016143B0>],
  'LDMODULEFLAGS': '$SHLINKFLAGS',
  'LDMODULEPREFIX': '$SHLIBPREFIX',
  'LDMODULESUFFIX': '$SHLIBSUFFIX',
  'LIBDIRPREFIX': '/LIBPATH:',
  'LIBDIRSUFFIX': '',
  'LIBLINKPREFIX': '',
  'LIBLINKSUFFIX': '$LIBSUFFIX',
  # 'LIBPATH': [ 'C:\\Cygwin\\home\\Administrator\\embedded-app-test\\build\\static'],
  'LIBPREFIX': '',
  'LIBPREFIXES': ['$LIBPREFIX'],
  'LIBS': [ 'libevent_core',
            'libevent',
            'libexslt',
            'libxslt',
            'libxml2',
            'sqlite3',
            'bz2',
            'charset',
            'iconv',
            'intl',
            'asprintf',
            'libeay32',
            'ssleay32',
            'zdll',
            'zlib'],
  'LIBSUFFIX': '.lib',
  'LIBSUFFIXES': ['$LIBSUFFIX'],
  'LINK': 'link',
  # 'LINKCOM': <SCons.Action.ListAction object at 0x01615510>,
  'LINKFLAGS': ['/nologo'],
  'MAXLINELENGTH': 2048,
  'MIDL': 'MIDL.EXE',
  'MIDLCOM': '$MIDL $MIDLFLAGS /tlb ${TARGETS[0]} /h ${TARGETS[1]} /iid ${TARGETS[2]} /proxy ${TARGETS[3]} /dlldata ${TARGETS[4]} $SOURCE 2> NUL',
  'MIDLFLAGS': ['/nologo'],
  'MSVC_SETUP_RUN': True,
  'MSVC_VERSION': '9.0',
  'MSVS': { 'PROJECTSUFFIX': '.vcproj', 'SOLUTIONSUFFIX': '.sln'},
  'MSVSBUILDCOM': '$MSVSSCONSCOM "$MSVSBUILDTARGET"',
  'MSVSCLEANCOM': '$MSVSSCONSCOM -c "$MSVSBUILDTARGET"',
  'MSVSENCODING': 'Windows-1252',
  # 'MSVSPROJECTCOM': <SCons.Action.FunctionAction object at 0x0160B870>,
  'MSVSPROJECTSUFFIX': '${GET_MSVSPROJECTSUFFIX}',
  'MSVSREBUILDCOM': '$MSVSSCONSCOM "$MSVSBUILDTARGET"',
  # 'MSVSSCONS': '"C:\\Cygwin\\home\\Administrator\\python\\bin\\python.exe" -c "from os.path import join; import sys; sys.path = [ join(sys.prefix, \'Lib\', \'site-packages\', \'scons-2.3.1\'), join(sys.prefix, \'scons-2.3.1\'), join(sys.prefix, \'Lib\', \'site-packages\', \'scons\'), join(sys.prefix, \'scons\') ] + sys.path; import SCons.Script; SCons.Script.main()"',
  'MSVSSCONSCOM': '$MSVSSCONS $MSVSSCONSFLAGS',
  # 'MSVSSCONSCRIPT': <SCons.Node.FS.File object at 0x01529FB0>,
  'MSVSSCONSFLAGS': '-C "${MSVSSCONSCRIPT.dir.abspath}" -f ${MSVSSCONSCRIPT.name}',
  # 'MSVSSOLUTIONCOM': <SCons.Action.FunctionAction object at 0x0160B890>,
  'MSVSSOLUTIONSUFFIX': '${GET_MSVSSOLUTIONSUFFIX}',
  'MSVS_VERSION': '9.0',
  'MT': 'mt',
  'MTEXECOM': '-$MT $MTFLAGS -manifest ${TARGET}.manifest $_MANIFEST_SOURCES -outputresource:$TARGET;1',
  'MTFLAGS': ['/nologo'],
  'MTSHLIBCOM': '-$MT $MTFLAGS -manifest ${TARGET}.manifest $_MANIFEST_SOURCES -outputresource:$TARGET;2',
  'OBJPREFIX': '',
  'OBJSUFFIX': '.obj',
  'PCHCOM': '$CXX /Fo${TARGETS[1]} $CXXFLAGS $CCFLAGS $CPPFLAGS $_CPPDEFFLAGS $_CPPINCFLAGS /c $SOURCES /Yc$PCHSTOP /Fp${TARGETS[0]} $CCPDBFLAGS $PCHPDBFLAGS',
  'PCHPDBFLAGS': ['${(PDB and "/Yd") or ""}'],
  # 'PIC_PYTHON_MODULES': True,
  # 'PIC_PYTHON_MODULE_ARRAY': False,
  # 'PIC_PYTHON_MODULE_AUDIOOP': False,
  # 'PIC_PYTHON_MODULE_BINASCII': False,
  # 'PIC_PYTHON_MODULE_BZ2': False,
  # 'PIC_PYTHON_MODULE_CMATH': False,
  # 'PIC_PYTHON_MODULE_CPICKLE': False,
  # 'PIC_PYTHON_MODULE_CRYPT': False,
  # 'PIC_PYTHON_MODULE_CSTRINGIO': False,
  # 'PIC_PYTHON_MODULE_DATETIME': False,
  # 'PIC_PYTHON_MODULE_DBM': False,
  # 'PIC_PYTHON_MODULE_ERRNO': False,
  # 'PIC_PYTHON_MODULE_FCNTL': False,
  # 'PIC_PYTHON_MODULE_FUTURE_BUILTINS': False,
  # 'PIC_PYTHON_MODULE_GC': False,
  # 'PIC_PYTHON_MODULE_GDBM': False,
  # 'PIC_PYTHON_MODULE_GRP': False,
  # 'PIC_PYTHON_MODULE_ITERTOOLS': False,
  # 'PIC_PYTHON_MODULE_LINUXAUDIODEV': False,
  # 'PIC_PYTHON_MODULE_MATH': False,
  # 'PIC_PYTHON_MODULE_MMAP': False,
  # 'PIC_PYTHON_MODULE_MSVCRT': False,
  # 'PIC_PYTHON_MODULE_NIS': False,
  # 'PIC_PYTHON_MODULE_NT': False,
  # 'PIC_PYTHON_MODULE_OPERATOR': False,
  # 'PIC_PYTHON_MODULE_OSSAUDIODEV': False,
  # 'PIC_PYTHON_MODULE_PARSER': False,
  # 'PIC_PYTHON_MODULE_POSIX': False,
  # 'PIC_PYTHON_MODULE_PWD': False,
  # 'PIC_PYTHON_MODULE_PYEXPAT': False,
  # 'PIC_PYTHON_MODULE_READLINE': False,
  # 'PIC_PYTHON_MODULE_RESOURCE': False,
  # 'PIC_PYTHON_MODULE_SELECT': False,
  # 'PIC_PYTHON_MODULE_SIGNAL': False,
  # 'PIC_PYTHON_MODULE_SPWD': False,
  # 'PIC_PYTHON_MODULE_STROP': False,
  # 'PIC_PYTHON_MODULE_SYSLOG': False,
  # 'PIC_PYTHON_MODULE_TERMIOS': False,
  # 'PIC_PYTHON_MODULE_THREAD': False,
  # 'PIC_PYTHON_MODULE_TIME': False,
  # 'PIC_PYTHON_MODULE_UNICODEDATA': False,
  # 'PIC_PYTHON_MODULE_XXSUBTYPE': False,
  # 'PIC_PYTHON_MODULE_ZIPIMPORT': False,
  # 'PIC_PYTHON_MODULE_ZLIB': False,
  # 'PIC_PYTHON_MODULE__BISECT': False,
  # 'PIC_PYTHON_MODULE__BSDDB': False,
  # 'PIC_PYTHON_MODULE__CODECS': False,
  # 'PIC_PYTHON_MODULE__CODECS_CN': False,
  # 'PIC_PYTHON_MODULE__CODECS_HK': False,
  # 'PIC_PYTHON_MODULE__CODECS_ISO2022': False,
  # 'PIC_PYTHON_MODULE__CODECS_JP': False,
  # 'PIC_PYTHON_MODULE__CODECS_KR': False,
  # 'PIC_PYTHON_MODULE__CODECS_TW': False,
  # 'PIC_PYTHON_MODULE__COLLECTIONS': False,
  # 'PIC_PYTHON_MODULE__CSV': False,
  # 'PIC_PYTHON_MODULE__CTYPES': False,
  # 'PIC_PYTHON_MODULE__CTYPES_TEST': False,
  # 'PIC_PYTHON_MODULE__CURSES': False,
  # 'PIC_PYTHON_MODULE__CURSES_PANEL': False,
  # 'PIC_PYTHON_MODULE__ELEMENTTREE': False,
  # 'PIC_PYTHON_MODULE__FUNCTOOLS': False,
  # 'PIC_PYTHON_MODULE__HASHLIB': False,
  # 'PIC_PYTHON_MODULE__HEAPQ': False,
  # 'PIC_PYTHON_MODULE__HOTSHOT': False,
  # 'PIC_PYTHON_MODULE__IO': False,
  # 'PIC_PYTHON_MODULE__JSON': False,
  # 'PIC_PYTHON_MODULE__LOCALE': False,
  # 'PIC_PYTHON_MODULE__LSPROF': False,
  # 'PIC_PYTHON_MODULE__MD5': False,
  # 'PIC_PYTHON_MODULE__MSI': False,
  # 'PIC_PYTHON_MODULE__MULTIBYTECODEC': False,
  # 'PIC_PYTHON_MODULE__MULTIPROCESSING': False,
  # 'PIC_PYTHON_MODULE__RANDOM': False,
  # 'PIC_PYTHON_MODULE__SCPROXY': False,
  # 'PIC_PYTHON_MODULE__SHA': False,
  # 'PIC_PYTHON_MODULE__SHA256': False,
  # 'PIC_PYTHON_MODULE__SHA512': False,
  # 'PIC_PYTHON_MODULE__SOCKET': False,
  # 'PIC_PYTHON_MODULE__SQLITE3': False,
  # 'PIC_PYTHON_MODULE__SRE': False,
  # 'PIC_PYTHON_MODULE__SSL': False,
  # 'PIC_PYTHON_MODULE__STRUCT': False,
  # 'PIC_PYTHON_MODULE__SUBPROCESS': False,
  # 'PIC_PYTHON_MODULE__SYMTABLE': False,
  # 'PIC_PYTHON_MODULE__TESTCAPI': False,
  # 'PIC_PYTHON_MODULE__TKINTER': False,
  # 'PIC_PYTHON_MODULE__WEAKREF': False,
  # 'PIC_PYTHON_MODULE__WINREG': False,
  'PLATFORM': 'win32',
  'PLATFORM_RELEASE': '2003Server',
  # 'PROGEMITTER': [<function prog_emitter at 0x016143F0>],
  'PROGPREFIX': '',
  'PROGSUFFIX': '.exe',
  # 'PSPAWN': <function piped_spawn at 0x01531FB0>,
  'PYTHON_DYNLOAD_FILE': None,
  # 'PYTHON_MODULES': [ [<SCons.Node.FS.File object at 0x01DD98F0>],
                      # [<SCons.Node.FS.File object at 0x01DD98F0>],
                      # [<SCons.Node.FS.File object at 0x01827550>],
                      # [<SCons.Node.FS.File object at 0x01832030>],
                      # [<SCons.Node.FS.File object at 0x01832AD0>],
                      # [<SCons.Node.FS.File object at 0x0183E690>],
                      # [<SCons.Node.FS.File object at 0x016F42F0>],
                      # [<SCons.Node.FS.File object at 0x016F4210>],
                      # [<SCons.Node.FS.File object at 0x01862B30>],
                      # [<SCons.Node.FS.File object at 0x0186B870>],
                      # [<SCons.Node.FS.File object at 0x0186B7D0>],
                      # [<SCons.Node.FS.File object at 0x01872570>],
                      # [<SCons.Node.FS.File object at 0x0187A330>],
                      # [<SCons.Node.FS.File object at 0x01892050>],
                      # [<SCons.Node.FS.File object at 0x01892F70>],
                      # [<SCons.Node.FS.File object at 0x0189BEB0>],
                      # [<SCons.Node.FS.File object at 0x0189BE10>],
                      # [<SCons.Node.FS.File object at 0x018CB030>],
                      # [<SCons.Node.FS.File object at 0x018CBF90>],
                      # [<SCons.Node.FS.File object at 0x018DB030>],
                      # [<SCons.Node.FS.File object at 0x018E2050>],
                      # [<SCons.Node.FS.File object at 0x018E90B0>],
                      # [<SCons.Node.FS.File object at 0x018F2270>],
                      # [<SCons.Node.FS.File object at 0x0193D6B0>],
                      # [<SCons.Node.FS.File object at 0x0193D5D0>],
                      # [<SCons.Node.FS.File object at 0x0194DCD0>],
                      # [<SCons.Node.FS.File object at 0x0195D190>],
                      # [<SCons.Node.FS.File object at 0x0195D250>],
                      # [<SCons.Node.FS.File object at 0x019654F0>],
                      # [<SCons.Node.FS.File object at 0x0196DA90>],
                      # [<SCons.Node.FS.File object at 0x019C1410>],
                      # [<SCons.Node.FS.File object at 0x019C1370>],
                      # [<SCons.Node.FS.File object at 0x019DD870>],
                      # [<SCons.Node.FS.File object at 0x019DD130>],
                      # [<SCons.Node.FS.File object at 0x01A2E750>],
                      # [<SCons.Node.FS.File object at 0x01A36F10>],
                      # [<SCons.Node.FS.File object at 0x01A448B0>],
                      # [<SCons.Node.FS.File object at 0x01AF2170>],
                      # [<SCons.Node.FS.File object at 0x01AF8970>],
                      # [<SCons.Node.FS.File object at 0x01AF89D0>],
                      # [<SCons.Node.FS.File object at 0x01B07350>],
                      # [<SCons.Node.FS.File object at 0x01C07730>],
                      # [<SCons.Node.FS.File object at 0x01C161F0>],
                      # [<SCons.Node.FS.File object at 0x01C1FCD0>],
                      # [<SCons.Node.FS.File object at 0x01C2E8F0>],
                      # [<SCons.Node.FS.File object at 0x01C2E810>],
                      # [<SCons.Node.FS.File object at 0x01C7B030>],
                      # [<SCons.Node.FS.File object at 0x01C7B070>],
                      # [<SCons.Node.FS.File object at 0x01C81C50>],
                      # [<SCons.Node.FS.File object at 0x01C9F790>],
                      # [<SCons.Node.FS.File object at 0x01C9F670>],
                      # [<SCons.Node.FS.File object at 0x01CEA3B0>],
                      # [<SCons.Node.FS.File object at 0x01D0B290>],
                      # [<SCons.Node.FS.File object at 0x01CF8290>],
                      # [<SCons.Node.FS.File object at 0x01D53850>],
                      # [<SCons.Node.FS.File object at 0x01D53210>],
                      # [<SCons.Node.FS.File object at 0x01D74A70>],
                      # [<SCons.Node.FS.File object at 0x01D74B10>],
                      # [<SCons.Node.FS.File object at 0x016D9670>]],
  # 'PYTHON_SOURCE_PATH': 'C:\\Cygwin\\home\\Administrator\\embedded-app-test\\build\\Python-2.7.6',
  'RC': 'rc',
  'RCCOM': '$RC $_CPPDEFFLAGS $_CPPINCFLAGS $RCFLAGS /fo$TARGET $SOURCES',
  'RCFLAGS': [],
  'RCSUFFIXES': ['.rc', '.rc2'],
  # 'RDirs': <SCons.Defaults.Variable_Method_Caller object at 0x0135DAD0>,
  'REGSVR': u'C:\\WINDOWS\\System32\\regsvr32',
  # 'REGSVRACTION': <SCons.Action.FunctionAction object at 0x016153D0>,
  'REGSVRCOM': '$REGSVR $REGSVRFLAGS ${TARGET.windows}',
  'REGSVRFLAGS': '/s ',
  'RMIC': 'rmic',
  'RMICCOM': '$RMIC $RMICFLAGS -d ${TARGET.attributes.java_lookupdir} -classpath ${SOURCE.attributes.java_classdir} ${SOURCES.attributes.java_classname}',
  'RMICFLAGS': [],
  'SCANNERS': [],
  'SCONS_HOME': None,
  # 'SHARED_PYTHON_MODULES': None,
  # 'SHARED_PYTHON_MODULE_ARRAY': False,
  # 'SHARED_PYTHON_MODULE_AUDIOOP': False,
  # 'SHARED_PYTHON_MODULE_BINASCII': False,
  # 'SHARED_PYTHON_MODULE_BZ2': False,
  # 'SHARED_PYTHON_MODULE_CMATH': False,
  # 'SHARED_PYTHON_MODULE_CPICKLE': False,
  # 'SHARED_PYTHON_MODULE_CRYPT': False,
  # 'SHARED_PYTHON_MODULE_CSTRINGIO': False,
  # 'SHARED_PYTHON_MODULE_DATETIME': False,
  # 'SHARED_PYTHON_MODULE_DBM': False,
  # 'SHARED_PYTHON_MODULE_ERRNO': False,
  # 'SHARED_PYTHON_MODULE_FCNTL': False,
  # 'SHARED_PYTHON_MODULE_FUTURE_BUILTINS': False,
  # 'SHARED_PYTHON_MODULE_GC': False,
  # 'SHARED_PYTHON_MODULE_GDBM': False,
  # 'SHARED_PYTHON_MODULE_GRP': False,
  # 'SHARED_PYTHON_MODULE_ITERTOOLS': False,
  # 'SHARED_PYTHON_MODULE_LINUXAUDIODEV': False,
  # 'SHARED_PYTHON_MODULE_MATH': False,
  # 'SHARED_PYTHON_MODULE_MMAP': False,
  # 'SHARED_PYTHON_MODULE_MSVCRT': False,
  # 'SHARED_PYTHON_MODULE_NIS': False,
  # 'SHARED_PYTHON_MODULE_NT': False,
  # 'SHARED_PYTHON_MODULE_OPERATOR': False,
  # 'SHARED_PYTHON_MODULE_OSSAUDIODEV': False,
  # 'SHARED_PYTHON_MODULE_PARSER': False,
  # 'SHARED_PYTHON_MODULE_POSIX': False,
  # 'SHARED_PYTHON_MODULE_PWD': False,
  # 'SHARED_PYTHON_MODULE_PYEXPAT': False,
  # 'SHARED_PYTHON_MODULE_READLINE': False,
  # 'SHARED_PYTHON_MODULE_RESOURCE': False,
  # 'SHARED_PYTHON_MODULE_SELECT': False,
  # 'SHARED_PYTHON_MODULE_SIGNAL': False,
  # 'SHARED_PYTHON_MODULE_SPWD': False,
  # 'SHARED_PYTHON_MODULE_STROP': False,
  # 'SHARED_PYTHON_MODULE_SYSLOG': False,
  # 'SHARED_PYTHON_MODULE_TERMIOS': False,
  # 'SHARED_PYTHON_MODULE_THREAD': False,
  # 'SHARED_PYTHON_MODULE_TIME': False,
  # 'SHARED_PYTHON_MODULE_UNICODEDATA': False,
  # 'SHARED_PYTHON_MODULE_XXSUBTYPE': False,
  # 'SHARED_PYTHON_MODULE_ZIPIMPORT': False,
  # 'SHARED_PYTHON_MODULE_ZLIB': False,
  # 'SHARED_PYTHON_MODULE__BISECT': False,
  # 'SHARED_PYTHON_MODULE__BSDDB': False,
  # 'SHARED_PYTHON_MODULE__CODECS': False,
  # 'SHARED_PYTHON_MODULE__CODECS_CN': False,
  # 'SHARED_PYTHON_MODULE__CODECS_HK': False,
  # 'SHARED_PYTHON_MODULE__CODECS_ISO2022': False,
  # 'SHARED_PYTHON_MODULE__CODECS_JP': False,
  # 'SHARED_PYTHON_MODULE__CODECS_KR': False,
  # 'SHARED_PYTHON_MODULE__CODECS_TW': False,
  # 'SHARED_PYTHON_MODULE__COLLECTIONS': False,
  # 'SHARED_PYTHON_MODULE__CSV': False,
  # 'SHARED_PYTHON_MODULE__CTYPES': False,
  # 'SHARED_PYTHON_MODULE__CTYPES_TEST': False,
  # 'SHARED_PYTHON_MODULE__CURSES': False,
  # 'SHARED_PYTHON_MODULE__CURSES_PANEL': False,
  # 'SHARED_PYTHON_MODULE__ELEMENTTREE': False,
  # 'SHARED_PYTHON_MODULE__FUNCTOOLS': False,
  # 'SHARED_PYTHON_MODULE__HASHLIB': False,
  # 'SHARED_PYTHON_MODULE__HEAPQ': False,
  # 'SHARED_PYTHON_MODULE__HOTSHOT': False,
  # 'SHARED_PYTHON_MODULE__IO': False,
  # 'SHARED_PYTHON_MODULE__JSON': False,
  # 'SHARED_PYTHON_MODULE__LOCALE': False,
  # 'SHARED_PYTHON_MODULE__LSPROF': False,
  # 'SHARED_PYTHON_MODULE__MD5': False,
  # 'SHARED_PYTHON_MODULE__MSI': False,
  # 'SHARED_PYTHON_MODULE__MULTIBYTECODEC': False,
  # 'SHARED_PYTHON_MODULE__MULTIPROCESSING': False,
  # 'SHARED_PYTHON_MODULE__RANDOM': False,
  # 'SHARED_PYTHON_MODULE__SCPROXY': False,
  # 'SHARED_PYTHON_MODULE__SHA': False,
  # 'SHARED_PYTHON_MODULE__SHA256': False,
  # 'SHARED_PYTHON_MODULE__SHA512': False,
  # 'SHARED_PYTHON_MODULE__SOCKET': False,
  # 'SHARED_PYTHON_MODULE__SQLITE3': False,
  # 'SHARED_PYTHON_MODULE__SRE': False,
  # 'SHARED_PYTHON_MODULE__SSL': False,
  # 'SHARED_PYTHON_MODULE__STRUCT': False,
  # 'SHARED_PYTHON_MODULE__SUBPROCESS': False,
  # 'SHARED_PYTHON_MODULE__SYMTABLE': False,
  # 'SHARED_PYTHON_MODULE__TESTCAPI': False,
  # 'SHARED_PYTHON_MODULE__TKINTER': False,
  # 'SHARED_PYTHON_MODULE__WEAKREF': False,
  # 'SHARED_PYTHON_MODULE__WINREG': False,
  'SHCC': '$CC',
  'SHCCCOM': '${TEMPFILE("$SHCC $_MSVC_OUTPUT_FLAG /c $CHANGED_SOURCES $SHCFLAGS $SHCCFLAGS $_CCCOMCOM")}',
  'SHCCFLAGS': ['$CCFLAGS'],
  'SHCFLAGS': ['$CFLAGS'],
  'SHCXX': '$CXX',
  'SHCXXCOM': '${TEMPFILE("$SHCXX $_MSVC_OUTPUT_FLAG /c $CHANGED_SOURCES $SHCXXFLAGS $SHCCFLAGS $_CCCOMCOM")}',
  'SHCXXFLAGS': ['$CXXFLAGS'],
  'SHELL': u'C:\\WINDOWS\\System32\\cmd.exe',
  'SHF03': '$F03',
  'SHF03COM': '$SHF03 -o $TARGET -c $SHF03FLAGS $_F03INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'SHF03FLAGS': ['$F03FLAGS'],
  'SHF03PPCOM': '$SHF03 -o $TARGET -c $SHF03FLAGS $CPPFLAGS $_CPPDEFFLAGS $_F03INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'SHF77': '$F77',
  'SHF77COM': '$SHF77 -o $TARGET -c $SHF77FLAGS $_F77INCFLAGS $SOURCES',
  'SHF77FLAGS': ['$F77FLAGS'],
  'SHF77PPCOM': '$SHF77 -o $TARGET -c $SHF77FLAGS $CPPFLAGS $_CPPDEFFLAGS $_F77INCFLAGS $SOURCES',
  'SHF90': '$F90',
  'SHF90COM': '$SHF90 -o $TARGET -c $SHF90FLAGS $_F90INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'SHF90FLAGS': ['$F90FLAGS'],
  'SHF90PPCOM': '$SHF90 -o $TARGET -c $SHF90FLAGS $CPPFLAGS $_CPPDEFFLAGS $_F90INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'SHF95': '$F95',
  'SHF95COM': '$SHF95 -o $TARGET -c $SHF95FLAGS $_F95INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'SHF95FLAGS': ['$F95FLAGS'],
  'SHF95PPCOM': '$SHF95 -o $TARGET -c $SHF95FLAGS $CPPFLAGS $_CPPDEFFLAGS $_F95INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'SHFORTRAN': '$FORTRAN',
  'SHFORTRANCOM': '$SHFORTRAN -o $TARGET -c $SHFORTRANFLAGS $_FORTRANINCFLAGS $_FORTRANMODFLAG $SOURCES',
  'SHFORTRANFLAGS': ['$FORTRANFLAGS'],
  'SHFORTRANPPCOM': '$SHFORTRAN -o $TARGET -c $SHFORTRANFLAGS $CPPFLAGS $_CPPDEFFLAGS $_FORTRANINCFLAGS $_FORTRANMODFLAG $SOURCES',
  # 'SHLIBEMITTER': [<function windowsLibEmitter at 0x01614370>],
  'SHLIBPREFIX': '',
  'SHLIBSUFFIX': '.dll',
  'SHLINK': '$LINK',
  # 'SHLINKCOM': <SCons.Action.ListAction object at 0x01615450>,
  'SHLINKFLAGS': ['$LINKFLAGS', '/dll'],
  'SHOBJPREFIX': '$OBJPREFIX',
  'SHOBJSUFFIX': '$OBJSUFFIX',
  # 'SPAWN': <function spawn at 0x015D9070>,
  # 'STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME': 1,
  # 'STATIC_PYTHON_MODULES': 1,
  # 'STATIC_PYTHON_MODULE_ARRAY': False,
  # 'STATIC_PYTHON_MODULE_AUDIOOP': False,
  # 'STATIC_PYTHON_MODULE_BINASCII': False,
  # 'STATIC_PYTHON_MODULE_BZ2': False,
  # 'STATIC_PYTHON_MODULE_CMATH': False,
  # 'STATIC_PYTHON_MODULE_CPICKLE': False,
  # 'STATIC_PYTHON_MODULE_CRYPT': False,
  # 'STATIC_PYTHON_MODULE_CSTRINGIO': False,
  # 'STATIC_PYTHON_MODULE_DATETIME': False,
  # 'STATIC_PYTHON_MODULE_DBM': False,
  # 'STATIC_PYTHON_MODULE_ERRNO': True,
  # 'STATIC_PYTHON_MODULE_FCNTL': False,
  # 'STATIC_PYTHON_MODULE_FUTURE_BUILTINS': False,
  # 'STATIC_PYTHON_MODULE_GC': True,
  # 'STATIC_PYTHON_MODULE_GDBM': False,
  # 'STATIC_PYTHON_MODULE_GRP': False,
  # 'STATIC_PYTHON_MODULE_INIT_FUNCS': [ u'cjson',
  #                                      u'cjson',
  #                                      '_codecs',
  #                                      'errno',
  #                                      'gc',
  #                                      'signal',
  #                                      '_sre',
  #                                      '_symtable',
  #                                      'nt',
  #                                      'thread',
  #                                      '_weakref',
  #                                      'xxsubtype',
  #                                      'zipimport',
  #                                      'array',
  #                                      'audioop',
  #                                      '_bisect',
  #                                      '_codecs_cn',
  #                                      '_codecs_hk',
  #                                      '_codecs_iso2022',
  #                                      '_codecs_jp',
  #                                      '_codecs_kr',
  #                                      '_codecs_tw',
  #                                      '_collections',
  #                                      'cPickle',
  #                                      'cStringIO',
  #                                      '_csv',
  #                                      'cmath',
  #                                      'datetime',
  #                                      '_functools',
  #                                      'future_builtins',
  #                                      '_heapq',
  #                                      '_hotshot',
  #                                      '_io',
  #                                      'itertools',
  #                                      '_json',
  #                                      '_locale',
  #                                      '_lsprof',
  #                                      'math',
  #                                      'mmap',
  #                                      '_multibytecodec',
  #                                      'operator',
  #                                      'parser',
  #                                      '_random',
  #                                      'strop',
  #                                      '_struct',
  #                                      '_testcapi',
  #                                      'time',
  #                                      'unicodedata',
  #                                      'binascii',
  #                                      'msvcrt',
  #                                      '_subprocess',
  #                                      '_winreg',
  #                                      '_ctypes',
  #                                      '_elementtree',
  #                                      'pyexpat',
  #                                      '_hashlib',
  #                                      'bz2',
  #                                      '_sqlite3',
  #                                      'zlib'],
  # 'STATIC_PYTHON_MODULE_ITERTOOLS': False,
  # 'STATIC_PYTHON_MODULE_LINUXAUDIODEV': False,
  # 'STATIC_PYTHON_MODULE_MATH': False,
  # 'STATIC_PYTHON_MODULE_MMAP': False,
  # 'STATIC_PYTHON_MODULE_MSVCRT': False,
  # 'STATIC_PYTHON_MODULE_NAMES': [ [<SCons.Node.FS.File object at 0x01DD98F0>],
                                  # [<SCons.Node.FS.File object at 0x01DD98F0>],
                                  # [<SCons.Node.FS.File object at 0x01827550>],
                                  # [<SCons.Node.FS.File object at 0x01832030>],
                                  # [<SCons.Node.FS.File object at 0x01832AD0>],
                                  # [<SCons.Node.FS.File object at 0x0183E690>],
                                  # [<SCons.Node.FS.File object at 0x016F42F0>],
                                  # [<SCons.Node.FS.File object at 0x016F4210>],
                                  # [<SCons.Node.FS.File object at 0x01862B30>],
                                  # [<SCons.Node.FS.File object at 0x0186B870>],
                                  # [<SCons.Node.FS.File object at 0x0186B7D0>],
                                  # [<SCons.Node.FS.File object at 0x01872570>],
                                  # [<SCons.Node.FS.File object at 0x0187A330>],
                                  # [<SCons.Node.FS.File object at 0x01892050>],
                                  # [<SCons.Node.FS.File object at 0x01892F70>],
                                  # [<SCons.Node.FS.File object at 0x0189BEB0>],
                                  # [<SCons.Node.FS.File object at 0x0189BE10>],
                                  # [<SCons.Node.FS.File object at 0x018CB030>],
                                  # [<SCons.Node.FS.File object at 0x018CBF90>],
                                  # [<SCons.Node.FS.File object at 0x018DB030>],
                                  # [<SCons.Node.FS.File object at 0x018E2050>],
                                  # [<SCons.Node.FS.File object at 0x018E90B0>],
                                  # [<SCons.Node.FS.File object at 0x018F2270>],
                                  # [<SCons.Node.FS.File object at 0x0193D6B0>],
                                  # [<SCons.Node.FS.File object at 0x0193D5D0>],
                                  # [<SCons.Node.FS.File object at 0x0194DCD0>],
                                  # [<SCons.Node.FS.File object at 0x0195D190>],
                                  # [<SCons.Node.FS.File object at 0x0195D250>],
                                  # [<SCons.Node.FS.File object at 0x019654F0>],
                                  # [<SCons.Node.FS.File object at 0x0196DA90>],
                                  # [<SCons.Node.FS.File object at 0x019C1410>],
                                  # [<SCons.Node.FS.File object at 0x019C1370>],
                                  # [<SCons.Node.FS.File object at 0x019DD870>],
                                  # [<SCons.Node.FS.File object at 0x019DD130>],
                                  # [<SCons.Node.FS.File object at 0x01A2E750>],
                                  # [<SCons.Node.FS.File object at 0x01A36F10>],
                                  # [<SCons.Node.FS.File object at 0x01A448B0>],
                                  # [<SCons.Node.FS.File object at 0x01AF2170>],
                                  # [<SCons.Node.FS.File object at 0x01AF8970>],
                                  # [<SCons.Node.FS.File object at 0x01AF89D0>],
                                  # [<SCons.Node.FS.File object at 0x01B07350>],
                                  # [<SCons.Node.FS.File object at 0x01C07730>],
                                  # [<SCons.Node.FS.File object at 0x01C161F0>],
                                  # [<SCons.Node.FS.File object at 0x01C1FCD0>],
                                  # [<SCons.Node.FS.File object at 0x01C2E8F0>],
                                  # [<SCons.Node.FS.File object at 0x01C2E810>],
                                  # [<SCons.Node.FS.File object at 0x01C7B030>],
                                  # [<SCons.Node.FS.File object at 0x01C7B070>],
                                  # [<SCons.Node.FS.File object at 0x01C81C50>],
                                  # [<SCons.Node.FS.File object at 0x01C9F790>],
                                  # [<SCons.Node.FS.File object at 0x01C9F670>],
                                  # [<SCons.Node.FS.File object at 0x01CEA3B0>],
                                  # [<SCons.Node.FS.File object at 0x01D0B290>],
                                  # [<SCons.Node.FS.File object at 0x01CF8290>],
                                  # [<SCons.Node.FS.File object at 0x01D53850>],
                                  # [<SCons.Node.FS.File object at 0x01D53210>],
                                  # [<SCons.Node.FS.File object at 0x01D74A70>],
                                  # [<SCons.Node.FS.File object at 0x01D74B10>],
                                  # [<SCons.Node.FS.File object at 0x016D9670>]],
  # 'STATIC_PYTHON_MODULE_NIS': False,
  # 'STATIC_PYTHON_MODULE_NT': True,
  # 'STATIC_PYTHON_MODULE_OBJECTS': [ [<SCons.Node.FS.File object at 0x01DD9710>],
                                    # [<SCons.Node.FS.File object at 0x01DD9710>],
                                    # [<SCons.Node.FS.File object at 0x0188FB50>],
                                    # [<SCons.Node.FS.File object at 0x01827FB0>],
                                    # [<SCons.Node.FS.File object at 0x01832A90>],
                                    # [<SCons.Node.FS.File object at 0x0183E630>],
                                    # [<SCons.Node.FS.File object at 0x016F4270>],
                                    # [<SCons.Node.FS.File object at 0x016F4EB0>],
                                    # [<SCons.Node.FS.File object at 0x01862AF0>],
                                    # [<SCons.Node.FS.File object at 0x0186B810>],
                                    # [<SCons.Node.FS.File object at 0x018725B0>],
                                    # [<SCons.Node.FS.File object at 0x0187A370>],
                                    # [<SCons.Node.FS.File object at 0x01881190>],
                                    # [<SCons.Node.FS.File object at 0x01881FB0>],
                                    # [<SCons.Node.FS.File object at 0x01892EF0>],
                                    # [<SCons.Node.FS.File object at 0x0189BE50>],
                                    # [<SCons.Node.FS.File object at 0x018C2ED0>],
                                    # [<SCons.Node.FS.File object at 0x018CBF50>],
                                    # [<SCons.Node.FS.File object at 0x018D3F50>],
                                    # [<SCons.Node.FS.File object at 0x018DBFF0>],
                                    # [<SCons.Node.FS.File object at 0x018E90F0>],
                                    # [<SCons.Node.FS.File object at 0x018F2230>],
                                    # [<SCons.Node.FS.File object at 0x019373B0>],
                                    # [<SCons.Node.FS.File object at 0x0193D630>],
                                    # [<SCons.Node.FS.File object at 0x01946930>],
                                    # [<SCons.Node.FS.File object at 0x0194DC50>],
                                    # [<SCons.Node.FS.File object at 0x0195D050>],
                                    # [<SCons.Node.FS.File object at 0x0195D150>],
                                    # [<SCons.Node.FS.File object at 0x01965530>],
                                    # [<SCons.Node.FS.File object at 0x01965610>],
                                    # [<SCons.Node.FS.File object at 0x0196DA30>],
                                    # [<SCons.Node.FS.File object at 0x019B3E90>],
                                    # [<SCons.Node.FS.File object at 0x019C13B0>],
                                    # [<SCons.Node.FS.File object at 0x019CA970>],
                                    # [<SCons.Node.FS.File object at 0x019DD090>],
                                    # [<SCons.Node.FS.File object at 0x019DD170>],
                                    # [<SCons.Node.FS.File object at 0x019DD2B0>],
                                    # [<SCons.Node.FS.File object at 0x019DD410>],
                                    # [<SCons.Node.FS.File object at 0x019DD570>],
                                    # [<SCons.Node.FS.File object at 0x019DD6B0>],
                                    # [<SCons.Node.FS.File object at 0x019DD7F0>],
                                    # [<SCons.Node.FS.File object at 0x019E9F30>],
                                    # [<SCons.Node.FS.File object at 0x01A2E6D0>],
                                    # [<SCons.Node.FS.File object at 0x01A36EB0>],
                                    # [<SCons.Node.FS.File object at 0x01A44750>],
                                    # [<SCons.Node.FS.File object at 0x01A44850>],
                                    # [<SCons.Node.FS.File object at 0x0195D050>],
                                    # [<SCons.Node.FS.File object at 0x01AF2130>],
                                    # [<SCons.Node.FS.File object at 0x01AF8930>],
                                    # [<SCons.Node.FS.File object at 0x01B072B0>],
                                    # [<SCons.Node.FS.File object at 0x01B0ECB0>],
                                    # [<SCons.Node.FS.File object at 0x01C076D0>],
                                    # [<SCons.Node.FS.File object at 0x01C16190>],
                                    # [<SCons.Node.FS.File object at 0x01C1FC90>],
                                    # [<SCons.Node.FS.File object at 0x01C2E870>],
                                    # [<SCons.Node.FS.File object at 0x01C3D470>],
                                    # [<SCons.Node.FS.File object at 0x01965610>],
                                    # [<SCons.Node.FS.File object at 0x01C81C90>],
                                    # [<SCons.Node.FS.File object at 0x01C91990>],
                                    # [<SCons.Node.FS.File object at 0x01C9F730>],
                                    # [<SCons.Node.FS.File object at 0x01CAF4F0>],
                                    # [<SCons.Node.FS.File object at 0x01CEA330>],
                                    # [<SCons.Node.FS.File object at 0x01CF82F0>],
                                    # [<SCons.Node.FS.File object at 0x01CF84F0>],
                                    # [<SCons.Node.FS.File object at 0x01CF8610>],
                                    # [<SCons.Node.FS.File object at 0x01CF8750>],
                                    # [<SCons.Node.FS.File object at 0x01CF88B0>],
                                    # [<SCons.Node.FS.File object at 0x01CF8CD0>],
                                    # [<SCons.Node.FS.File object at 0x01CF8ED0>],
                                    # [<SCons.Node.FS.File object at 0x01D0B0D0>],
                                    # [<SCons.Node.FS.File object at 0x01D0B210>],
                                    # [<SCons.Node.FS.File object at 0x01D1A1F0>],
                                    # [<SCons.Node.FS.File object at 0x01D53270>],
                                    # [<SCons.Node.FS.File object at 0x01D53470>],
                                    # [<SCons.Node.FS.File object at 0x01D53670>],
                                    # [<SCons.Node.FS.File object at 0x01D537D0>],
                                    # [<SCons.Node.FS.File object at 0x01D658F0>],
                                    # [<SCons.Node.FS.File object at 0x01D74A30>],
                                    # [<SCons.Node.FS.File object at 0x01D83D50>],
                                    # [<SCons.Node.FS.File object at 0x01D83F10>],
                                    # [<SCons.Node.FS.File object at 0x01DB6070>],
                                    # [<SCons.Node.FS.File object at 0x01DB6170>],
                                    # [<SCons.Node.FS.File object at 0x01DB62B0>],
                                    # [<SCons.Node.FS.File object at 0x01DB63B0>],
                                    # [<SCons.Node.FS.File object at 0x01DB64F0>],
                                    # [<SCons.Node.FS.File object at 0x01DB6630>],
                                    # [<SCons.Node.FS.File object at 0x01DB6770>],
                                    # [<SCons.Node.FS.File object at 0x016D9550>]],
  # 'STATIC_PYTHON_MODULE_OPERATOR': False,
  # 'STATIC_PYTHON_MODULE_OSSAUDIODEV': False,
  # 'STATIC_PYTHON_MODULE_PARSER': False,
  # 'STATIC_PYTHON_MODULE_POSIX': True,
  # 'STATIC_PYTHON_MODULE_PWD': False,
  # 'STATIC_PYTHON_MODULE_PYEXPAT': False,
  # 'STATIC_PYTHON_MODULE_READLINE': False,
  # 'STATIC_PYTHON_MODULE_RESOURCE': False,
  # 'STATIC_PYTHON_MODULE_SELECT': False,
  # 'STATIC_PYTHON_MODULE_SIGNAL': True,
  # 'STATIC_PYTHON_MODULE_SPWD': False,
  # 'STATIC_PYTHON_MODULE_STROP': False,
  # 'STATIC_PYTHON_MODULE_SYSLOG': False,
  # 'STATIC_PYTHON_MODULE_TERMIOS': False,
  # 'STATIC_PYTHON_MODULE_THREAD': True,
  # 'STATIC_PYTHON_MODULE_TIME': False,
  # 'STATIC_PYTHON_MODULE_UNICODEDATA': False,
  # 'STATIC_PYTHON_MODULE_XXSUBTYPE': True,
  # 'STATIC_PYTHON_MODULE_ZIPIMPORT': True,
  # 'STATIC_PYTHON_MODULE_ZLIB': False,
  # 'STATIC_PYTHON_MODULE__BISECT': False,
  # 'STATIC_PYTHON_MODULE__BSDDB': False,
  # 'STATIC_PYTHON_MODULE__CODECS': True,
  # 'STATIC_PYTHON_MODULE__CODECS_CN': False,
  # 'STATIC_PYTHON_MODULE__CODECS_HK': False,
  # 'STATIC_PYTHON_MODULE__CODECS_ISO2022': False,
  # 'STATIC_PYTHON_MODULE__CODECS_JP': False,
  # 'STATIC_PYTHON_MODULE__CODECS_KR': False,
  # 'STATIC_PYTHON_MODULE__CODECS_TW': False,
  # 'STATIC_PYTHON_MODULE__COLLECTIONS': False,
  # 'STATIC_PYTHON_MODULE__CSV': False,
  # 'STATIC_PYTHON_MODULE__CTYPES': False,
  # 'STATIC_PYTHON_MODULE__CTYPES_TEST': False,
  # 'STATIC_PYTHON_MODULE__CURSES': False,
  # 'STATIC_PYTHON_MODULE__CURSES_PANEL': False,
  # 'STATIC_PYTHON_MODULE__ELEMENTTREE': False,
  # 'STATIC_PYTHON_MODULE__FUNCTOOLS': False,
  # 'STATIC_PYTHON_MODULE__HASHLIB': False,
  # 'STATIC_PYTHON_MODULE__HEAPQ': False,
  # 'STATIC_PYTHON_MODULE__HOTSHOT': False,
  # 'STATIC_PYTHON_MODULE__IO': False,
  # 'STATIC_PYTHON_MODULE__JSON': False,
  # 'STATIC_PYTHON_MODULE__LOCALE': False,
  # 'STATIC_PYTHON_MODULE__LSPROF': False,
  # 'STATIC_PYTHON_MODULE__MD5': False,
  # 'STATIC_PYTHON_MODULE__MSI': False,
  # 'STATIC_PYTHON_MODULE__MULTIBYTECODEC': False,
  # 'STATIC_PYTHON_MODULE__MULTIPROCESSING': False,
  # 'STATIC_PYTHON_MODULE__RANDOM': False,
  # 'STATIC_PYTHON_MODULE__SCPROXY': False,
  # 'STATIC_PYTHON_MODULE__SHA': False,
  # 'STATIC_PYTHON_MODULE__SHA256': False,
  # 'STATIC_PYTHON_MODULE__SHA512': False,
  # 'STATIC_PYTHON_MODULE__SOCKET': False,
  # 'STATIC_PYTHON_MODULE__SQLITE3': False,
  # 'STATIC_PYTHON_MODULE__SRE': True,
  # 'STATIC_PYTHON_MODULE__SSL': False,
  # 'STATIC_PYTHON_MODULE__STRUCT': False,
  # 'STATIC_PYTHON_MODULE__SUBPROCESS': False,
  # 'STATIC_PYTHON_MODULE__SYMTABLE': True,
  # 'STATIC_PYTHON_MODULE__TESTCAPI': False,
  # 'STATIC_PYTHON_MODULE__TKINTER': False,
  # 'STATIC_PYTHON_MODULE__WEAKREF': True,
  # 'STATIC_PYTHON_MODULE__WINREG': False,
  'TARGET_ARCH': 'x86',
  'TARGET_OS': None,
  # 'TEMPFILE': <class 'SCons.Platform.TempFileMunge'>,
  'TEMPFILEPREFIX': '@',
  'TOOLS': [ 'default',
             'mslink',
             'msvc',
             'gfortran',
             'masm',
             'mslib',
             'msvs',
             'midl',
             'filesystem',
             'jar',
             'javac',
             'rmic',
             'zip'],
  'UNICODE_SIZE': '2',
  'VERSION': '27',
  'WIN32DEFPREFIX': '',
  'WIN32DEFSUFFIX': '.def',
  'WIN32EXPPREFIX': '',
  'WIN32EXPSUFFIX': '.exp',
  'WIN32_INSERT_DEF': 0,
  'WINDOWSDEFPREFIX': '${WIN32DEFPREFIX}',
  'WINDOWSDEFSUFFIX': '${WIN32DEFSUFFIX}',
  'WINDOWSEXPPREFIX': '${WIN32EXPPREFIX}',
  'WINDOWSEXPSUFFIX': '${WIN32EXPSUFFIX}',
  'WINDOWSPROGMANIFESTPREFIX': '',
  'WINDOWSPROGMANIFESTSUFFIX': '${PROGSUFFIX}.manifest',
  'WINDOWSSHLIBMANIFESTPREFIX': '',
  'WINDOWSSHLIBMANIFESTSUFFIX': '${SHLIBSUFFIX}.manifest',
  'WINDOWS_EMBED_MANIFEST': 0,
  'WINDOWS_INSERT_DEF': '${WIN32_INSERT_DEF}',
  # 'WITH_DL': True,
  # 'WITH_DOC_STRINGS': True,
  # 'WITH_IPV6': True,
  # 'WITH_PYDEBUG': False,
  # 'WITH_PYMALLOC': True,
  # 'WITH_PYTHON_MODULE_ARRAY': True,
  # 'WITH_PYTHON_MODULE_AUDIOOP': True,
  # 'WITH_PYTHON_MODULE_BINASCII': True,
  # 'WITH_PYTHON_MODULE_BZ2': True,
  # 'WITH_PYTHON_MODULE_CMATH': True,
  # 'WITH_PYTHON_MODULE_CPICKLE': True,
  # 'WITH_PYTHON_MODULE_CRYPT': True,
  # 'WITH_PYTHON_MODULE_CSTRINGIO': True,
  # 'WITH_PYTHON_MODULE_DATETIME': True,
  # 'WITH_PYTHON_MODULE_DBM': True,
  # 'WITH_PYTHON_MODULE_ERRNO': True,
  # 'WITH_PYTHON_MODULE_FCNTL': True,
  # 'WITH_PYTHON_MODULE_FUTURE_BUILTINS': True,
  # 'WITH_PYTHON_MODULE_GC': True,
  # 'WITH_PYTHON_MODULE_GDBM': True,
  # 'WITH_PYTHON_MODULE_GRP': True,
  # 'WITH_PYTHON_MODULE_ITERTOOLS': True,
  # 'WITH_PYTHON_MODULE_LINUXAUDIODEV': True,
  # 'WITH_PYTHON_MODULE_MATH': True,
  # 'WITH_PYTHON_MODULE_MMAP': True,
  # 'WITH_PYTHON_MODULE_MSVCRT': True,
  # 'WITH_PYTHON_MODULE_NIS': False,
  # 'WITH_PYTHON_MODULE_NT': True,
  # 'WITH_PYTHON_MODULE_OPERATOR': True,
  # 'WITH_PYTHON_MODULE_OSSAUDIODEV': True,
  # 'WITH_PYTHON_MODULE_PARSER': True,
  # 'WITH_PYTHON_MODULE_POSIX': True,
  # 'WITH_PYTHON_MODULE_PWD': True,
  # 'WITH_PYTHON_MODULE_PYEXPAT': True,
  # 'WITH_PYTHON_MODULE_READLINE': True,
  # 'WITH_PYTHON_MODULE_RESOURCE': True,
  # 'WITH_PYTHON_MODULE_SELECT': True,
  # 'WITH_PYTHON_MODULE_SIGNAL': True,
  # 'WITH_PYTHON_MODULE_SPWD': True,
  # 'WITH_PYTHON_MODULE_STROP': True,
  # 'WITH_PYTHON_MODULE_SYSLOG': True,
  # 'WITH_PYTHON_MODULE_TERMIOS': True,
  # 'WITH_PYTHON_MODULE_THREAD': True,
  # 'WITH_PYTHON_MODULE_TIME': True,
  # 'WITH_PYTHON_MODULE_UNICODEDATA': True,
  # 'WITH_PYTHON_MODULE_XXSUBTYPE': True,
  # 'WITH_PYTHON_MODULE_ZIPIMPORT': True,
  # 'WITH_PYTHON_MODULE_ZLIB': True,
  # 'WITH_PYTHON_MODULE__BISECT': True,
  # 'WITH_PYTHON_MODULE__BSDDB': True,
  # 'WITH_PYTHON_MODULE__CODECS': True,
  # 'WITH_PYTHON_MODULE__CODECS_CN': True,
  # 'WITH_PYTHON_MODULE__CODECS_HK': True,
  # 'WITH_PYTHON_MODULE__CODECS_ISO2022': True,
  # 'WITH_PYTHON_MODULE__CODECS_JP': True,
  # 'WITH_PYTHON_MODULE__CODECS_KR': True,
  # 'WITH_PYTHON_MODULE__CODECS_TW': True,
  # 'WITH_PYTHON_MODULE__COLLECTIONS': True,
  # 'WITH_PYTHON_MODULE__CSV': True,
  # 'WITH_PYTHON_MODULE__CTYPES': True,
  # 'WITH_PYTHON_MODULE__CTYPES_TEST': False,
  # 'WITH_PYTHON_MODULE__CURSES': True,
  # 'WITH_PYTHON_MODULE__CURSES_PANEL': True,
  # 'WITH_PYTHON_MODULE__ELEMENTTREE': True,
  # 'WITH_PYTHON_MODULE__FUNCTOOLS': True,
  # 'WITH_PYTHON_MODULE__HASHLIB': True,
  # 'WITH_PYTHON_MODULE__HEAPQ': True,
  # 'WITH_PYTHON_MODULE__HOTSHOT': True,
  # 'WITH_PYTHON_MODULE__IO': True,
  # 'WITH_PYTHON_MODULE__JSON': True,
  # 'WITH_PYTHON_MODULE__LOCALE': True,
  # 'WITH_PYTHON_MODULE__LSPROF': True,
  # 'WITH_PYTHON_MODULE__MD5': True,
  # 'WITH_PYTHON_MODULE__MSI': True,
  # 'WITH_PYTHON_MODULE__MULTIBYTECODEC': True,
  # 'WITH_PYTHON_MODULE__MULTIPROCESSING': True,
  # 'WITH_PYTHON_MODULE__RANDOM': True,
  # 'WITH_PYTHON_MODULE__SCPROXY': True,
  # 'WITH_PYTHON_MODULE__SHA': True,
  # 'WITH_PYTHON_MODULE__SHA256': True,
  # 'WITH_PYTHON_MODULE__SHA512': True,
  # 'WITH_PYTHON_MODULE__SOCKET': True,
  # 'WITH_PYTHON_MODULE__SQLITE3': True,
  # 'WITH_PYTHON_MODULE__SRE': True,
  # 'WITH_PYTHON_MODULE__SSL': True,
  # 'WITH_PYTHON_MODULE__STRUCT': True,
  # 'WITH_PYTHON_MODULE__SUBPROCESS': True,
  # 'WITH_PYTHON_MODULE__SYMTABLE': True,
  # 'WITH_PYTHON_MODULE__TESTCAPI': True,
  # 'WITH_PYTHON_MODULE__TKINTER': True,
  # 'WITH_PYTHON_MODULE__WEAKREF': True,
  # 'WITH_PYTHON_MODULE__WINREG': True,
  # 'WITH_READLINE': True,
  # 'WITH_SHARED': True,
  # 'WITH_THREAD': True,
  # 'WITH_TSC': False,
  # 'WITH_UNICODE': True,
  # 'WITH_VALGRIND': False,
  'WIXCANDLE': 'candle.exe',
  'WIXLIGHT': 'light.exe',
  'XFLAGS': '',
  'ZIP': 'zip',
  # 'ZIPCOM': <SCons.Action.FunctionAction object at 0x01644810>,
  'ZIPCOMPRESSION': 8,
  'ZIPFLAGS': [],
  'ZIPROOT': [],
  'ZIPSUFFIX': '.zip',
  '_CCCOMCOM': '$CPPFLAGS $_CPPDEFFLAGS $_CPPINCFLAGS $CCPCHFLAGS $CCPDBFLAGS',
  '_CPPDEFFLAGS': '${_defines(CPPDEFPREFIX, CPPDEFINES, CPPDEFSUFFIX, __env__)}',
  '_CPPINCFLAGS': '$( ${_concat(INCPREFIX, CPPPATH, INCSUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
  '_F03INCFLAGS': '$( ${_concat(INCF03PREFIX, F03PATH, INCF03SUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
  '_F77INCFLAGS': '$( ${_concat(INCF77PREFIX, F77PATH, INCF77SUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
  '_F90INCFLAGS': '$( ${_concat(INCF90PREFIX, F90PATH, INCF90SUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
  '_F95INCFLAGS': '$( ${_concat(INCF95PREFIX, F95PATH, INCF95SUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
  '_FORTRANINCFLAGS': '$( ${_concat(INCFORTRANPREFIX, FORTRANPATH, INCFORTRANSUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
  '_FORTRANMODFLAG': '$( ${_concat(FORTRANMODDIRPREFIX, FORTRANMODDIR, FORTRANMODDIRSUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
  '_JARCOM': '$JAR $_JARFLAGS $TARGET $_JARMANIFEST $_JARSOURCES',
  # '_JARFLAGS': <function jarFlags at 0x0163B630>,
  # '_JARMANIFEST': <function jarManifest at 0x0163B5F0>,
  # '_JARSOURCES': <function jarSources at 0x0163B570>,
  '_JAVABOOTCLASSPATH': '${_javapathopt("-bootclasspath", "JAVABOOTCLASSPATH")} ',
  '_JAVACCOM': '$JAVAC $JAVACFLAGS $_JAVABOOTCLASSPATH $_JAVACLASSPATH -d ${TARGET.attributes.java_classdir} $_JAVASOURCEPATH $SOURCES',
  '_JAVACLASSPATH': '${_javapathopt("-classpath", "JAVACLASSPATH")} ',
  '_JAVASOURCEPATH': '${_javapathopt("-sourcepath", "JAVASOURCEPATH", "_JAVASOURCEPATHDEFAULT")} ',
  '_JAVASOURCEPATHDEFAULT': '${TARGET.attributes.java_sourcedir}',
  # '_LDMODULE_SOURCES': <function _windowsLdmodSources at 0x016142F0>,
  # '_LDMODULE_TARGETS': <function _windowsLdmodTargets at 0x016142B0>,
  '_LIBDIRFLAGS': '$( ${_concat(LIBDIRPREFIX, LIBPATH, LIBDIRSUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
  '_LIBFLAGS': '${_concat(LIBLINKPREFIX, LIBS, LIBLINKSUFFIX, __env__)}',
  '_MANIFEST_SOURCES': None,
  # '_MSVC_OUTPUT_FLAG': <function msvc_output_flag at 0x0160DEF0>,
  # '_PDB': <function pdbGenerator at 0x01614170>,
  # '_SHLINK_SOURCES': <function windowsShlinkSources at 0x01614270>,
  # '_SHLINK_TARGETS': <function windowsShlinkTargets at 0x01614230>,
  # '_concat': <function _concat at 0x0135FBF0>,
  # '_defines': <function _defines at 0x0135FCF0>,
  # '_javapathopt': <class 'SCons.Tool.javac.pathopt'>,
  # '_stripixes': <function _stripixes at 0x0135FC70>}
}
